### ISSUE TITLE
react-slidedown import should use tilda

### ISSUE THREAD

**Issue by metadan** [azouaoui-med/react-pro-sidebar#1]
file: src/scss/styles.scss

Please swap 

@import '../../node_modules/react-slidedown/lib/slidedown.css';

to 

@import '~react-slidedown/lib/slidedown.css';

so that when importing scss into another project file it doesn't break the import

**Comment by azouaoui-med** [comment]
That's much cleaner .. thank you :)

**Comment by metadan** [comment]
You're welcome. Thanks for the useful component
