### ISSUE TITLE
"link to"  not working in MenuItem

### ISSUE THREAD

**Issue by soma1204** [azouaoui-med/react-pro-sidebar#101]
<SubMenu >
          <MenuItem > 
          Inventory
  <Link to="/inventory" />
</MenuItem>
           </SubMenu>

Navigation PATH is not changing when i click on "Inventory" on sidebar.
current-->http://localhost:3000/
expected: http://localhost:3000/inventory

**Comment by EliotAmn** [comment]
same

**Comment by azouaoui-med** [comment]
please provide a minimum code to highlight the issue, also you may wanna create [codesandbox](https://codesandbox.io/)  sample demo

**Comment by soma1204** [comment]
Hi ,

I didn’t get you. Path is not changing when I click on menuItem. When I add
“link to” sidebar disappears.
Could you please help on if any tuning needs to be installed.


Thanks
Soma
