### ISSUE TITLE
Change colors when using CSS

### ISSUE THREAD

**Issue by victorkvarghese** [azouaoui-med/react-pro-sidebar#110]
How can i change global colors used in this library if i'm only using CSS. My Project doesnt allow us to use SCSS.

**Comment by azouaoui-med** [comment]
you can use css selector to override the existing css 
ex : 
```
.pro-sidebar {
    color: #ffffff;
}
```

**Comment by victorkvarghese** [comment]
okay, but i will have to override the colors everywhere right?
