### ISSUE TITLE
Removing  of react-slidedown?

### ISSUE THREAD

**Issue by erikpa1** [azouaoui-med/react-pro-sidebar#114]
Hi I see you are using react-slidedown, but that library died 3 years ago, is it possible to rewrite it to get new functionality from react 18 (which is also necessary for react fiber and drei :D )?

**Comment by azouaoui-med** [comment]
a new version is being developed and almost done, checkout it out here [https://github.com/azouaoui-med/react-pro-sidebar/tree/v1](https://github.com/azouaoui-med/react-pro-sidebar/tree/v1)

**Comment by erikpa1** [comment]
@azouaoui-med  thanks for answer, I solved it by coping libraries I need to my project (because external libraries requires react-dom, event they dont need it, and react-slidedown keeps my react-dom on low level so other libraries cant be included) but thanks god, libraries I use are mostly like 2-3 files :D
