### ISSUE TITLE
Menu in SidebarFooter

### ISSUE THREAD

**Issue by alejandroastudillo** [azouaoui-med/react-pro-sidebar#12]
Hi @azouaoui-med. Thank you very much for this really nice sidebar. It has been really helpful for my personal academic website I'm currently building.

I have two questions for you. 
I'm trying to set a Menu with two MenuItems (Settings, Log out) that sticks to the bottom of the sidebar. For that, I'm trying to put the Menu inside the SidebarFooter like this
```
            <SidebarFooter >            
                    <Menu >
                        <MenuItem icon={<FaCog />}>
                            Settings
                        </MenuItem>

                        <MenuItem icon={<FaSignOutAlt />}> 
                            Log out
                        </MenuItem>
                    </Menu>
            </SidebarFooter>
```
but the Menu is being pushed down, and thus the sidebar becomes scrollable as you can see in the attached images.
![sidebar_wfooter1](https://user-images.githubusercontent.com/17018006/90060928-b7f30500-dce5-11ea-8ff9-8706d70f16bc.png)

**After scrolling the sidebar down:**
![sidebar_wfooter2](https://user-images.githubusercontent.com/17018006/90060938-b9bcc880-dce5-11ea-9f0e-d9a66ef5b33f.png)

I have tried to modify the style of `.pro-sidebar .pro-sidebar-inner .pro-sidebar-footer { }` but haven't succeed to get the footer menu stuck to the bottom (pushing up the `border-top line` in the footer). Can you please guide me on how can I achieve this?

On the other hand, is it possible to have the SidebarContent automatically scrollable? Like, if I open several SubMenus and I don't want to push the footer down but scroll inside the SidebarContent container.

Thanks in advance.

**Comment by azouaoui-med** [comment]
Fixed in [v0.4.4](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v0.4.4)
