### ISSUE TITLE
Missing styles.css

### ISSUE THREAD

**Issue by mikku489** [azouaoui-med/react-pro-sidebar#123]
This bug was opened earlier in 2020, fixed but now seems to be back.

>**Module not found: Can't resolve 'react-pro-sidebar/dist/css/styles.css'**
> 5 | import { ProSidebar, Menu, MenuItem, SubMenu } from 'react-pro-sidebar';
> 6 | import 'react-pro-sidebar/dist/css/styles.css';

maybe some compilation step is missing that's required to generate the styles.css?

**Comment by mikku489** [comment]
Fixed by downgrading to 0.7.1

**Comment by azouaoui-med** [comment]
import css file is deprecated in[ v1](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v1.0.0-alpha.1) in favor of css in js, v1 is still in alpha and not yet stable
