### ISSUE TITLE
Submenu items not showing when Sidebar is collapsed

### ISSUE THREAD

**Issue by jphilips22** [azouaoui-med/react-pro-sidebar#124]
The Submenu (v. 1.0.0-alpha.3) does not expand once the sidebar is collapsed. I did use the example in the Readme.md file
[Codesandbox demo](https://codesandbox.io/s/sidebar-nnv2vk?file=/src/Layout.js)

**Comment by azouaoui-med** [comment]
issue fixed in version 1.0.0-alpha.6
