### ISSUE TITLE
How to achieve previous look ?

### ISSUE THREAD

**Issue by erikpa1** [azouaoui-med/react-pro-sidebar#127]
Hi I'm already using v.1, (because of dependencies)

but not sure if I understand right. In 0.7 version I had header, content nad footer, but in v1 I don't see anything like this, Will it be added later, or this functionality will not be supported ? 

![image](https://user-images.githubusercontent.com/19526670/195834176-37147fbf-b520-4f8e-9f71-94a34fed89d0.png)

Now it looks like this:

![image](https://user-images.githubusercontent.com/19526670/195834366-39474f94-ebf8-4abf-a3c7-32cbbf397439.png)

Also I used something like:

```
                <sb.MenuItem icon={<FcContacts/>}>
                    {t("core.contact")}
                    <Link to={"/contact"}/>
                </sb.MenuItem>
```
which worket with my react HashRouter pretty nice. If I understand right this should be switched to onClick ?

**Comment by mattvb91** [comment]
I have to agree with @erikpa1 here, tried to upgrade due to react 18 deps but if all of these components are missing ill just be removing this package altogether because the benefit was that it looked great just from the get go

**Comment by azouaoui-med** [comment]
The purpose of removing layout components is to keep the library clean from unnecessary additions, and i don't see that this components are adding much value since they are super easy to implement,  and also because they only serve one of the many forms of layouts that can be implemented

to implement the previous layout you can just do the following :
```jsx
<Sidebar>
 <div style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
   <div>header</div>
   <div style={{ flex: 1 }}>content</div>
   <div>footer</div>
 </div>
</Sidebar>
```
