### ISSUE TITLE
Compatibility with React router

### ISSUE THREAD

**Issue by andreash** [azouaoui-med/react-pro-sidebar#129]
react-pro-sidebar generate an anchor element ("<a>") for each menu item. A console warning is generated, if a NavLink  or Link is used within a Menu Item, as it also generates an anchor element and anchor elements  shouldn't be nested.

I think it would be great, if react-pro-sidebar could be made compatible with react-router in some way. I.e. there could be a react-router compatible version of MenuItem which also plays the role of a Link / NavLink.

But may be I didn't fully understand the idea within react-pro-sidebare and there actually is some compatibility which I just didn't realize?

Best,
Andreas

**Comment by azouaoui-med** [comment]
A new prop is added to `MenuItem` component called `routerLink` which adds support to react router's `Link` / `NavLink` components 

**example usage :**

```tsx
import { Sidebar, Menu, MenuItem } from 'react-pro-sidebar';
import { Link } from 'react-router-dom';

<Sidebar>
  <Menu>
    <MenuItem routerLink={<Link to="/documentation" />}> Documentation</MenuItem>
    <MenuItem routerLink={<Link to="/calendar" />}> Calendar</MenuItem>
    <MenuItem routerLink={<Link to="/e-commerce" />}> E-commerce</MenuItem>
  </Menu>
</Sidebar>;
```

**Note:** only tested with react router version 6 and still in experimental stage

**Comment by secret-knight** [comment]
Hi, 

Do you think you could add support to NextJS's Link as well? It would be much appreciated!

Thanks
