### ISSUE TITLE
Toggle button not showing upon click on collapse button in demo.

### ISSUE THREAD

**Issue by jeffersonwilliam** [azouaoui-med/react-pro-sidebar#130]
I was trying the playground code and I noticed this behavior. The collapse button shows in all states, be it toggled or collapsed. I believe that's not how it's intended to function, and I was wondering if there was a fix to it.

[demo](https://azouaoui-med.github.io/react-pro-sidebar/iframe.html?id=playground--playground&args=&viewMode=story)

**Comment by azouaoui-med** [comment]
showing or hiding collapse button when sidebar hits breakpoint is completely up to you, you have access to the `broken` state via  `useProSidebar` which you can use as a condition to do that 

in playground (demo) you can update the code to this :
```tsx
{broken && (
   <button
    className="sb-button"
    style={{ marginRight: '8px' }}
    onClick={() => collapseSidebar()}
   >
    Collapse
   </button>
)}
```
