### ISSUE TITLE
Submenu not working on Safari in collapsed mode

### ISSUE THREAD

**Issue by rbalaga** [azouaoui-med/react-pro-sidebar#132]
**Describe the bug**
Sub-menu list is not visible when Sidebar is collapsed, and submenu is opened.

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Browser: Safari
 - Version: verified in >13 versions.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone10]
 - OS: [iOS14]
 - Browser [safari]

**Comment by azouaoui-med** [comment]
tested on safari version 14 on mac and seems to work fine, can you make sure you have the latest version of the package
