### ISSUE TITLE
How to change menu item hover background color?

### ISSUE THREAD

**Issue by mm-dsibinski** [azouaoui-med/react-pro-sidebar#133]
**Describe the bug**
After upgrading from `0.7.1` to `1.0.0-alpha.7`, all the UI is broken. I assume this is mostly because of this change:

```
Removed scss in favor of css-in-js(styled component)
```

I'd like to change the background color of the menu item on hover, which is always white.

**To Reproduce**
I have my sidebar rendered:

```tsx

<ProSidebar backgroundColor="#252529" width="220px">
        <Menu>
          <MenuItem icon={<MyIconComponent/>}>
            <a href="https://some-url">{"MenuItem"}</a>
          </MenuItem>
        </Menu>
      </ProSidebar>
```

Previously, I could override SCSS variables to change the menu item background color on hovering. Let's say I want this color to be `red`. I tried setting it like that:

```tsx
<Menu
          renderMenuItemStyles={(params) => {
            return { backgroundColor: "red" };
          }}
        >
```

but still, the background is always white on mouse hover.

I also tried adding this in my SCSS file:

```cscc
.menu-item:hover {
  background-color: red;
}
```

but it also has no effect.

How can I change the menu item hover background color in the newest version?

**Comment by azouaoui-med** [comment]
you can use renderMenuItemStyles to override menu item styling 
for your request using the following should work 

   ```jsx
 <Menu renderMenuItemStyles={() => ({
      '.menu-anchor': {
           backgroundColor: 'red',
           '&:hover': {
              backgroundColor: 'green',
           },
       },
 })}
>
```

as a note this prop will give access to all MenuItems and sub menus and all child nodes

also worth mentioning that classes and prop behavior is under review and may change in the upcoming releases

**Comment by mm-dsibinski** [comment]
hi @azouaoui-med , thank you for answering. This does the job.

I have two other remarks for the current version.

1. Error about styled-components initialization
I also use styled-components in my app, and now I'm getting a warning:

```
base.js:46 It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles to not render properly, errors during the rehydration process, a missing theme prop, and makes your application bigger without good reason.

See https://s-c.sh/2BAXzed for more info.
```

2. Issue with `a` (anchors)
I have my menu items declared as follows:

```tsx
<ProSidebar backgroundColor="#252529" width="220px">
          <MenuItem icon={<MyIconComponent/>}>
            <a href="https://some-url">My menu item</a>
          </MenuItem>
      </ProSidebar>
```

I'm getting the following error:

```
index.js:1 Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
```

that's because there are indeed two `a` tags in the current structure rendered by `react-pro-sidebar`:

![image](https://user-images.githubusercontent.com/49182064/202111138-f2fd266b-b3a8-4b70-ad7d-9ecf2ee4ba17.png)

I didn't find any good example in the documentation how to place normal menu items clickable links, without using `a` tag (without using react router)

**Comment by mm-dsibinski** [comment]
@azouaoui-med I see that the API changed again between `1.0.0-alpha.7` and current `1.0.0-beta.2`. The `renderMenuItemStyles` on `Menu` component doesn't exist anymore.

I found [here](https://azouaoui-med.github.io/react-pro-sidebar/?path=/docs/menu--menu-item-styles) that there's a new property called `menuItemStyles`. However, how to apply it for the use case from this issue?

**Comment by azouaoui-med** [comment]
with new prop you can target directly child nodes as follow :

```jsx
<Menu menuItemStyles={{
  button: {
        backgroundColor: 'red',
        '&:hover': {
           backgroundColor: 'green',
        },
    },
}}
>
```

make sure you checkout the [playground](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/storybook/Playground.tsx) code, it covers most of the use cases

**Comment by shahriarhossain** [comment]
@azouaoui-med :
```
<Menu menuItemStyles={{
  button: {
        backgroundColor: 'red',
         '&:hover': {
                backgroundColor: '#d8f3dc',
                color: '#1b4332'
              },
    },
}}
>
```
This works! Thanks.

But can we do it from sass?

**Comment by azouaoui-med** [comment]
@shahriarhossain yes you can override the styles by accessing the items via class names 

find used classes [here](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/src/utils/utilityClasses.ts)

**Comment by lavanyakumarallu** [comment]
@azouaoui-med 

How can we add custom styles to SubMenu like the syntax below

```
<Menu menuItemStyles={{
  button: {
        backgroundColor: 'red',
         '&:hover': {
                backgroundColor: '#d8f3dc',
                color: '#1b4332'
              },
    },
}}
>
```

**Comment by azouaoui-med** [comment]
if you are trying to have custom styles on only submenu components you can use a function definition instead of object as follow :
```jsx
<Menu menuItemStyles={{
  button: ({isSubmenu, level, disabled, active, open }) =>({
    backgroundColor: isSubmenu ? 'red' : undefined,
 }),
}}
>
```
you can take advantage of the params you get from the function to customize the items from MenuItem/SubMenu components

in the example above you have access to `isSubmenu` param to use as a condition for styling

on top of that you can still use utility classes to access the items by starting from the root element 

here is the type definition of `menuItemStyles` prop
```jsx
interface MenuItemStyles {
  root?: ElementStyles;
  button?: ElementStyles;
  label?: ElementStyles;
  prefix?: ElementStyles;
  suffix?: ElementStyles;
  icon?: ElementStyles;
  subMenuContent?: ElementStyles;
  SubMenuExpandIcon?: ElementStyles;
}

type ElementStyles = CSSObject | ((params: MenuItemStylesParams) => CSSObject | undefined);

interface MenuItemStylesParams {
  level: number;
  disabled: boolean;
  active: boolean;
  isSubmenu: boolean;
  open?: boolean;
}

export type ElementStyles = CSSObject | ((params: MenuItemStylesParams) => CSSObject | undefined);
```

**Comment by sanaryaa** [comment]
@azouaoui-med I try this code but it does not work 
`<Menu menuItemStyles={{
  button: {
        backgroundColor: 'red',
         '&:hover': {
                backgroundColor: '#d8f3dc',
                color: '#1b4332'
              },
    },
}}
> `
what should I do ,can you tell me?

**Comment by wandieinnocents** [comment]
> ```js
> menuItemStyles={{
>   button: {
>         backgroundColor: 'red',
>         '&:hover': {
>            backgroundColor: 'green',
>         },
>     },
> }}
> ```

This works
