### ISSUE TITLE
Submenu label not working

### ISSUE THREAD

**Issue by AkshanviC** [azouaoui-med/react-pro-sidebar#135]
**Describe the bug**
Submenu label is not working

**To Reproduce**
when you create a submenu and even if you provide label attribute to the component, the label is not rendered in the screen (even label attribute is not suggested in vs code snippet)

**Expected behavior**
Needed to show the label of the submenu

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome,

**Comment by azouaoui-med** [comment]
You are probably using [v0.x](https://github.com/azouaoui-med/react-pro-sidebar/tree/v0.x), checkout the docs here [here](https://github.com/azouaoui-med/react-pro-sidebar/tree/v0.x)

**Comment by AkshanviC** [comment]
Thanks man. means a lot. great work
