### ISSUE TITLE
(not bug): Can't find documentation on why I'm seeing a pro-react-sidebar::marker by default

### ISSUE THREAD

**Issue by drewboardman** [azouaoui-med/react-pro-sidebar#138]
![Screen Shot 2022-12-20 at 11 18 29 AM](https://user-images.githubusercontent.com/8429384/208714783-d5fa3e4e-6b9b-4617-a137-e576aa24a7f1.png)
![Screen Shot 2022-12-20 at 11 18 16 AM](https://user-images.githubusercontent.com/8429384/208714792-d3f1757f-1630-4eba-9285-630561878d30.png)

I'm seeing a `marker` showing up by using the default pro-react-sidebar documentation. Here is an example of a component that using `<MenuItem>` that is displaying this `::marker`.

```
interface ItemProps {
  title: string;
  to: string;
  icon: ReactElement;
  selected: string;
  setSelected: Dispatch<SetStateAction<string>>;
}

function Item(props: ItemProps): ReactElement {
  const theme = useTheme();
  const colors = tokens(theme.palette.mode);
  return (
    <MenuItem
      active={props.selected === props.title}
      style={{ color: colors.grey[100] }}
      onClick={() => props.setSelected(props.title)}
      icon={props.icon}
    >
      <Typography>{props.title}</Typography>
      <Link to={props.to} />
    </MenuItem>
  );
}
```

I'm not seeing a prop for the `MenuItem` component that allows disabling of this marker. Any idea on how to turn it off?

**Comment by azouaoui-med** [comment]
this is added by default to ul li elements, and it is removed by adding `list-style-type: none;` css property to ul element

it seems that you are using version 0.x, so you should import css file to apply the necessary styles for the sidebar

check the docs for v0.x [here](https://github.com/azouaoui-med/react-pro-sidebar/tree/v0.x)

**Comment by drewboardman** [comment]
Ah, I see. That's also probably why I don't have `ProSidebarProvider` either.

Thanks.
