### ISSUE TITLE
Supporting custom widths of the sidebar

### ISSUE THREAD

**Issue by alexowen34** [azouaoui-med/react-pro-sidebar#145]
Hello!

**Describe the bug**

I am defining a custom width of the sidebar and I am also using the toggle sidebar feature. When toggling off the menu e.g. by clicking on a different part of the screen and when the menu is not at the default width, the menu does not fully hide itself. 

**To Reproduce**

1. Create sidebar and define the width wider than the default
2. Enable the toggle feature
3. Toggle onto the sidebar in the UI.
4. Then toggle off the sidebar by clicking on a different part of the screen (you should see that the sidebar does not fully hide itself)

**Expected behavior**

Expected the menu to be fully hidden, however the difference between the default width and custom width still shows on the screen. 

Also, is there a way to set the sidebar to be automatically toggled/visable when the component loads?

**Comment by azouaoui-med** [comment]
can you please share how you are setting the custom width !
you need to use sidebar's width prop as follow:
```jsx
<Sidebar width="300px" ...
```

**Comment by alexowen34** [comment]
@azouaoui-med 

Thanks for getting back to me - I'm setting the custom width via the below

```
<Sidebar style={{width:'auto', border:'none'}} breakPoint='always'>
```
I've tried using the width prop directly e.g. the below, however this appears to remove the toggle functionality and the side bar is permanently displayed.

```
<Sidebar width='auto' style={{border:'none'}} breakPoint='always'>
```

**Comment by azouaoui-med** [comment]
the with needs to be set explicitly as i mentioned, the sidebar should have a fixed width
 
```jsx
<Sidebar width="300px" ...
```

also setting `breakPoint="always"` will activate toggle behavior on all screen sizes

**Comment by alexowen34** [comment]
@azouaoui-med 

Thanks for clarifying - its working now that I set an explicit width.

Is there any way for the width to be automatic based on the content size? I'm populating the sidebar dynamically so I won't always know the width of the content inside it

**Comment by azouaoui-med** [comment]
The package doesn't automatically infer the width of the sidebar at the moment, you can try using refs to set the width dynamically 

for example :
```jsx
 React.useLayoutEffect(() => {
    setWidth(sidebarRef.current.offsetWidth);
  }, []);
```
