### ISSUE TITLE
ProSidebarProvider is required

### ISSUE THREAD

**Issue by randerso21** [azouaoui-med/react-pro-sidebar#146]
**Describe the bug**
Here is my code
import {
  Sidebar,
  Menu,
  MenuItem,
} from "react-pro-sidebar";

  return ( 
      <div style={{ display: 'flex', height: '100%' }}>
        <Sidebar>
          <Menu>
            <MenuItem icon={<FontAwesomeIcon icon={faHome} />}>Documentation</MenuItem>
            <MenuItem icon={<FontAwesomeIcon icon={faGears} />}> Calendar</MenuItem>
            <MenuItem icon={<FontAwesomeIcon icon={faDatabase} />}> E-commerce</MenuItem>
            <MenuItem icon={<FontAwesomeIcon icon={faHome} />}> Examples</MenuItem>
          </Menu>
        </Sidebar>
      </div>
  );
Fairly simple, but when trying to display 

![image](https://user-images.githubusercontent.com/92995482/216710124-86aa6daa-b09c-4622-b9e0-8896f8a7805c.png)

**To Reproduce**
1. Go to the page that has the above code
2. let the page load
3. See error

**Expected behavior**
I expect to see the page with the sidebar and not just a white screen

**Screenshots**

**Desktop (please complete the following information):**
 - Linux
 - Browser Firefox
 - Version 109.0.1

**Additional context**

**Comment by randerso21** [comment]
Not sure if the code posted correctly, but I got it from
https://azouaoui-med.github.io/react-pro-sidebar/?path=/docs/menuitem--with-icon

**Comment by azouaoui-med** [comment]
in your App.jsx wrap your components with `ProSidebarProvider` ...

```jsx
<ProSidebarProvider>
    ...
</ProSidebarProvider>
```

make sure you checkout the usage examples in the readme file

**Comment by randerso21** [comment]
Thanks for your help
