### ISSUE TITLE
closeOnClick is not closing the subMenus

### ISSUE THREAD

**Issue by gfortin6** [azouaoui-med/react-pro-sidebar#147]
**Describe the bug**
I tried the closeOnClick feature on the demo presented in the documentation
 ```
<Sidebar>
  <Menu closeOnClick>
    <SubMenu label="Charts">
      <MenuItem> Pie charts </MenuItem>
      <MenuItem> Line charts </MenuItem>
    </SubMenu>
    <SubMenu label="Charts2">
      <MenuItem> Pie charts </MenuItem>
      <MenuItem> Line charts </MenuItem>
    </SubMenu>
    <MenuItem> Documentation </MenuItem>
    <MenuItem> Calendar </MenuItem>
  </Menu>
</Sidebar>
```

**To Reproduce**
1. Click on SubMenu1
2. Click on SubMenu2
3. Both Submenus are opened
the same happen on the click of the menuItem if a SubMenu is open.

**Expected behavior**
I was expecting the opened submenu to close when I click on one of the other menuItem/SubMenu.
The menu should keep only one subMenu opened at all time

My app is build on React 18.0.27
Pro-side-bar version 1.0.0

thank you and keep up the good work

**Comment by azouaoui-med** [comment]
`closeOnClick` prop will only work when sidebar is in collapsed state, so when clicking on `MenuItem` inside a popper, the popper will close automatically 

![image](https://user-images.githubusercontent.com/25878302/216762205-25429d2a-4a22-443f-9a87-191b5a8fe730.png)
