### ISSUE TITLE
How can I wrap text?

### ISSUE THREAD

**Issue by vinsis** [azouaoui-med/react-pro-sidebar#148]
Thank you for providing such a great library.

I am using it in one of my projects. I would like to wrap the text instead of adding ellipsis. But I haven't been able to figure out how. Is there any quick way to achieve that?

<img width="287" alt="Screenshot 2023-02-05 at 4 51 54 PM" src="https://user-images.githubusercontent.com/6437295/216810049-10449245-77df-474f-9f21-5c3df7b3b2eb.png">

**Comment by vinsis** [comment]
I believe it has something to do with [these values](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/src/styles/StyledMenuLabel.tsx#L9-L11)

**Comment by azouaoui-med** [comment]
you can use the `menuItemStyles` prop to override MenuItem nodes styles 
```jsx
 <Sidebar>
      <Menu
        menuItemStyles={{
           label: {
                  // apply / override styles of all menu item labels
           }
        }}

```
