### ISSUE TITLE
Prosidebar is blocking child component

### ISSUE THREAD

**Issue by Cyrelc** [azouaoui-med/react-pro-sidebar#150]
**Describe the bug**
A searchbar with asynchronous results is having the top 5-6 results blocked, only when included in the sidebar. They are visibly there, but cannot be selected or clicked on, and this only occurs when included in the sidebar, regardless of position (header, footer, body)

I have attempted to overwrite the z-index, with no improvements

**Expected behavior**
I can click on any rendered option

**Screenshots**
https://user-images.githubusercontent.com/15618831/217883559-731c9959-0db6-4a70-9b3c-d89ebc19861f.mp4

**Desktop (please complete the following information):**
 - OS: Windows (client) / Ubuntu (server)
 - Browser: Chrome

**Comment by azouaoui-med** [comment]
@Cyrelc can you share a code snippet that we can use to debug the issue ?!

**Comment by Cyrelc** [comment]
Thanks for getting back to me @azouaoui-med 

Just went to try to create a code sandbox, and am not seeing it, but I'm using version 0.7, I didn't notice the 1.0 release. 

I'm attempting to update my code to 1.0 to see if that solves it, but looks like quite a bit of the nice functionality (dark mode, hover to open submenus instead of click) was removed for 1.0... so I have to see what I can do on my end, I'd prefer not to open a ticket for you on an "older" version, but I was heavily using darkmode and hover. Bear with me while I explore my options

**Comment by Cyrelc** [comment]
Confirmed the new version does not have the same issue - thank you for your time, and very sorry to have bothered you
