### ISSUE TITLE
Sticky sidebar and remove right border

### ISSUE THREAD

**Issue by pyrotechnik** [azouaoui-med/react-pro-sidebar#153]
Good day,
no matter how hard I try, the fixed position of the Sidebar does not work for me. I don't know where exactly to put the sticks. I also have a problem with removing the right border at: 
```
ps-sidebar-root.css-1wvake5 {
position: relative;
border-right-width: 1px; ----- i need 0px
.
.
}
```

For example, I change the colors like this:

```
sx={{
        "& .MuiBox-root": {
              background: `${colors.primary[400]} !important`,
         },
}}
```

**Comment by azouaoui-med** [comment]
to remove the border, you can use `rootStyles` prop  as follow 
```jsx
<Sidebar
  rootStyles={{
    border: 'none',
  }}
```

not sure what kind issue you are getting about the sticky part, but thats something that should be handled via your layout setup

**Comment by KanoDekouBillyBrown** [comment]
when using @0.7.1 i made a state handler that would collapse and expand the sidebar whenever a button is pressed , but after updating the package it doesn't work anymore . i tried importing collapseSidebar and using it but it doesn't work

**Comment by azouaoui-med** [comment]
in v1.x, the collpased state is handled internally for you, and to update the state you just need to call `collapseSidebar` function

you need to wrap your app with `ProSidebarProvider` component

**Comment by KanoDekouBillyBrown** [comment]
That's understood pretty well , when using onClick` { () => collapseSidebar() }` it collapses the sidebar successfully but when i use the toggleSidebar function the state of the sidebar doesn't change when i click a button is it an error ?

**Comment by azouaoui-med** [comment]
you can get the state from the hook, `useProSidebar`, 
it would be better if you share relevant code so we can quickly detect the issue

**Comment by KanoDekouBillyBrown** [comment]
Thank you for your concern I finally made the code to work using the collapsed state

**Comment by dolevelbaz** [comment]
@pyrotechnik can you share how you made the fixed position work for you?

**Comment by sarahdepalo** [comment]
@pyrotechnik 
I had success using the following:
```
 <Sidebar
        rootStyles={{
          border: 'none',
          position: 'sticky',
          top: 0,
          height: '100vh',
          overflow: 'auto',
        }}
      >
```

My sidebar is also wrapped in a container along with the main content
```
<ProSidebarProvider>
        <div className="mainContainer">
            <SideMenu megaMenu={megaMenu} />
            <main className="mainContainer__content">
              <Component {...pageProps} />
            </main>
        </div>
  </ProSidebarProvider>
```
