### ISSUE TITLE
Using react-pro-sidebar with Next.js, the React.js framework

### ISSUE THREAD

**Issue by SandroSimonOre** [azouaoui-med/react-pro-sidebar#154]
Hi,

I'm implementing react-pro-sidebar in Next.js since this framework is built on top of React.js. Specifically I was trying to include a Link (next/link from Next.js, not the one from react-router-dom) like this:

```
<MenuItem >
       <Link href='/dashboard'>
            Dashboard
       </Link>                    
</MenuItem>
```

But it is throwing me the error 

> Error: Hydration failed because the initial UI does not match what was rendered on the server.

So, I changed my code and it looks like this:

```
<MenuItem  onClick={()=> router.push('/dashboard')} > 
Dashboard                  
</MenuItem>
```
Now it works. But I still have a doubt if that is the correct way to use react-pro-sidebar.

**Comment by azouaoui-med** [comment]
try using the component prop 
```jsx
 <MenuItem component={<Link href="/dashboard" />}>Dashboard</MenuItem>
```

**Comment by SandroSimonOre** [comment]
Thank you, now it is working.
