### ISSUE TITLE
Initial collapsed state is always false on the initial render

### ISSUE THREAD

**Issue by ocimer** [azouaoui-med/react-pro-sidebar#155]
**Describe the bug**
Initial state of the collapsed value is always false on the initial render (only), even when "defaultCollapsed" prop is set.

**To Reproduce**
1. Go to [sanbox](https://codesandbox.io/s/default-collapsed-initial-state-h58ufo)
2. Refresh the page in the web view area and observe the console and the web view area. 
3. In the web view you will clearly see a jump from not collapsed to collapsed on page refresh, and the console will output "false"  on initial render and "true" after.

**Expected behavior**
With the "defaultCollapsed" prop set I expect the sidebar to be collapsed even on the initial render.

**Desktop (please complete the following information):**
Any modern browser

**Comment by Ishadir** [comment]
https://user-images.githubusercontent.com/73375508/231544896-757d1797-b5a4-461a-9b26-8c34fcac45cb.mp4


i think it's happening to me too.

**Comment by Ishadir** [comment]
https://user-images.githubusercontent.com/73375508/231545263-1dbb8010-4a7f-4b7c-a898-72e77eb36ec0.mp4

same here, im using defaultCollapsed true and this happends when i refresh the page with f5 or i enter the first time.
