### ISSUE TITLE
Sidebar height

### ISSUE THREAD

**Issue by Neuroforge** [azouaoui-med/react-pro-sidebar#158]
Hello,

I am trying to get the sidebar to be 100% height.

This was previously addressed in https://github.com/azouaoui-med/react-pro-sidebar/issues/63 however the ProSideBar -> Sidebasr changes appear to be different.

Here is what i've tried using the sidebarClasses utility but it does not appear to render the way intended.

      <Sidebar
        defaultCollapsed={isCollapsed}
        rootStyles={{
          [`.${sidebarClasses.container}`]: {
            backgroundColor: "#ffffff",
          },
          [`.${sidebarClasses.root}`]: {
            height: "100vh !important",
          },
        }}
      >

I cannot seem to see the height being applied in the console.

<img width="1136" alt="Screenshot 2023-03-29 at 12 20 19 pm" src="https://user-images.githubusercontent.com/1474186/228401951-420457ac-b20a-4a0c-ac2c-5d9f2af650b5.png">

Is there a solution to this for the newer api?

If i force the height in the console for this element, i get the outcome that i want. How to do this programatically using the the style utilities.

Regards,

**Comment by Neuroforge** [comment]
Hmmmm.

Solved...

      <Sidebar
        defaultCollapsed={isCollapsed}
        rootStyles={{
          [`.${sidebarClasses.container}`]: {
            backgroundColor: "#ffffff",
            height: "100vh !important",
          },
          [`.${sidebarClasses.root}`]: {},
        }}
      >

**Comment by psygo** [comment]
This doesn't seem to be working for me. I've created an [SO question here](https://stackoverflow.com/q/78251904/4756173).

**Comment by azouaoui-med** [comment]
to apply styles on the root element of the sidebar you can directly set it in rootStyles object 
```
  <Sidebar
    defaultCollapsed={isCollapsed}
    rootStyles={{
        height:"100vh",
    }}
  >
```

or add the & to the selector 
```
  <Sidebar
    defaultCollapsed={isCollapsed}
    rootStyles={{
         [`&.${sidebarClasses.root}`]: {
             height:"100vh",
         },      
    }}
  >
```

also `backgroundColor` is available as a prop on the sidebar component, you can refer to API table in the docs
