### ISSUE TITLE
Submenu "drop down arrow"

### ISSUE THREAD

**Issue by theneweracoder** [azouaoui-med/react-pro-sidebar#16]
![IMG_20200919_012020](https://user-images.githubusercontent.com/39115077/93639250-532e7700-fa16-11ea-8bda-473b29036c81.jpg)

The library is really useful, and I've used your demo code for reference to make a page of my own...
I want the arrows marked in the image on the text and on the "Dropdown arrow " to be aligned in a single line, but there's no way/code of doing that.. I hope it's an internal error..
A pre-thanks if you can help me out xD...

**Comment by azouaoui-med** [comment]
The arrow is by default aligned with the text, you may need to share a codesandbox to highlight the error

**Comment by theneweracoder** [comment]
> The arrow is by default aligned with the text, you may need to share a codesandbox to highlight the error

Okay will share it in a while.

**Comment by theneweracoder** [comment]
![specific css ](https://user-images.githubusercontent.com/39115077/94373192-62ea4180-0121-11eb-8e71-111214688852.png)
![general css](https://user-images.githubusercontent.com/39115077/94373194-641b6e80-0121-11eb-8298-ba84368a24bc.png)
![tsx file](https://user-images.githubusercontent.com/39115077/94373197-64b40500-0121-11eb-8532-d606621446e9.png)
these are the code files

**Comment by tsanyqudsi** [comment]
@theneweracoder why would you assign classname on the menu ?
