### ISSUE TITLE
Scroller disable (scrolling)

### ISSUE THREAD

**Issue by robozb** [azouaoui-med/react-pro-sidebar#160]
Dear Community, 

How can I disable the default scrolling function? I'd like to let the sidebar to fill the vertical space as It wants. I don't want it to use scrollbar.

Thanks: Bela

![image](https://user-images.githubusercontent.com/8656998/231246021-df30f469-f7be-43a3-851f-28c496c8f955.png)

**Comment by nazmulweb** [comment]
You can remove it by passing a border none props on the Sidebar like below 

`<Sidebar
  rootStyles={{
    border: 'none',
  }}> 
.......
</Sidebar>
` 

To get more details visit here #153

**Comment by robozb** [comment]
> You can remove it by passing a border none props on the Sidebar like below
> 
> `<Sidebar rootStyles={{ border: 'none', }}> ....... </Sidebar> `
> 
> To get more details visit here #153

Thanks!
