### ISSUE TITLE
useProSidebar

### ISSUE THREAD

**Issue by zroussama** [azouaoui-med/react-pro-sidebar#163]
export 'useProSidebar' (imported as 'useProSidebar') was not found in 'react-pro-sidebar' (possible exports: Menu, MenuItem, ProSidebar, SidebarContent, SidebarFooter, SidebarHeader, SubMenu)

` <ProSidebar collapsed={isCollapsed}>
....
  </ProSidebar>`

**Comment by azouaoui-med** [comment]
`useProSidebar` is only available in v1, and you seem to have v0 installed

**Comment by zroussama** [comment]
Thank you
