### ISSUE TITLE
Initial Render Issue

### ISSUE THREAD

**Issue by irtaza9** [azouaoui-med/react-pro-sidebar#164]
**Describe the bug**
When I refresh I face the below attached issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: latest

https://user-images.githubusercontent.com/98938307/235580298-9045b035-23fb-4db2-a6c6-a519484e2c86.mp4

**Comment by JonneBR** [comment]
I haven't had this problem before, now one of my pages suffers this layout shift.

**Comment by azouaoui-med** [comment]
a fix was added to v [1.1.0-alpha.1](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v1.1.0-alpha.1)

**Comment by irtaza9** [comment]
when it'll be merged?

**Comment by azouaoui-med** [comment]
its merged and published, just need to install it on your side by specifying the version

**Comment by irtaza9** [comment]
Does it's ok to use `ProSidebarProvider` in [1.1.0-alpha.1](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v1.1.0-alpha.1) version?

![image](https://github.com/azouaoui-med/react-pro-sidebar/assets/98938307/7911d6e0-8d61-446d-b11d-28404d5fa895)

and is it fine?

![image](https://github.com/azouaoui-med/react-pro-sidebar/assets/98938307/5a1cefa3-95d6-4c50-81b7-0f83aa2f59ae)

Here it is mentioned that the provider is deprecated?

![image](https://github.com/azouaoui-med/react-pro-sidebar/assets/98938307/ebbd9ea7-9c36-4078-8787-0861122a7bbe)

and what about this?
  
![image](https://github.com/azouaoui-med/react-pro-sidebar/assets/98938307/9d23f408-56a8-475e-9ba2-1f79d724e90a)

what should we use?

**Comment by azouaoui-med** [comment]
its still okay to use them but it will be removed in the next major version (v2) since its causing unnecessary render on mount! i recommend using the new props  (collapsed, toggled,...) and remove the provider

please check the [playground](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/storybook/Playground.tsx) code for a reference

**Comment by irtaza9** [comment]
Yes  [playground](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/storybook/Playground.tsx)  helps a lot when something is changed. Now I have to make a common component where Both sidebar and Appbar is rendered so to handle the toggle event of sidebar from Appbar. 



```javascript
import { Box } from "@mui/material";
import { Outlet } from "react-router-dom";
import PortalSidebar from "./Sidebar";
import Topbar from "./TopAppbar";
import { useState } from "react";

const InnerContent = () => {
  const [toggled, setToggled] = useState(false);
  const [broken, setBroken] = useState(false);

  return (
    <Box display={"flex"}>
      <Box>
        <PortalSidebar
          toggled={toggled}
          setToggled={setToggled}
          setBroken={setBroken}
          broken={broken}
        />
      </Box>
      <Box flexGrow={1} minHeight={"100vh"}>
        <Topbar broken={broken} toggled={toggled} setToggled={setToggled} />
        <Box pl={2}>
          <Outlet />
        </Box>
      </Box>
    </Box>
  );
};

export default InnerContent;
``` 

Thank you Mohammad <3
