### ISSUE TITLE
Close button when toggled

### ISSUE THREAD

**Issue by plamenh** [azouaoui-med/react-pro-sidebar#166]
**Is your feature request related to a problem? Please describe.**
Having to click on the backdrop to close the sidebar is not intuitive.

**Describe the solution you'd like**
Add (the option of) a close button.

**Describe alternatives you've considered**
None

**Additional context**
<img width="294" alt="Screenshot 2023-05-11 at 15 48 24" src="https://github.com/azouaoui-med/react-pro-sidebar/assets/14073311/c938f1cf-8458-43ec-bd1f-4a12e0bd2674">

**Comment by azouaoui-med** [comment]
most drawers, sidebars, dialogs, poppers have the pattern of closing when clicking outside or on backdrop 
so it should be intuitive enough !

NOTE: working on new updates where toggle state will be controlled by user, also it may be useful to add option to disable backdrop !
