### ISSUE TITLE
Sub Menu on Click Flash of Collapsed State

### ISSUE THREAD

**Issue by emanuallan** [azouaoui-med/react-pro-sidebar#173]
**Describe the bug**
When I click on a sub-menu item the menu experiences a rerender in a quick instance that displays the menu in all collapsed state.

Video: https://www.awesomescreenshot.com/video/18083401?key=3cc8c68609e46e8233a3e45261f413cb

Implementation details:
![Screenshot 2023-06-06 at 12 36 01 PM](https://github.com/azouaoui-med/react-pro-sidebar/assets/22531461/912be45d-7d0c-4559-8b41-2ca42b4a3714)

**Comment by azouaoui-med** [comment]
can you share a codesandbox sample with the issue mentioned ?!
