### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by dibyendumca** [azouaoui-med/react-pro-sidebar#177]
Hello,

I tried to install the **React-Pro-Sidebar** package with the below command.
`npm install react-pro-sidebar --force`

It installed with some dependency warnings..
Then when I tried to run it from VS Code Terminal with
`npm start`

I got stucked after some message as below.....
```

> rollup v2.79.1
> bundles src/index.ts → dist/index.js, dist/index.es.js...
> created dist/index.js, dist/index.es.js in 5.2s
> 
> [2023-06-15 11:40:48] waiting for changes...

```

**Comment by azouaoui-med** [comment]
it seems that you are trying to run the package via rollup, if you wish to run storybook, use `npm run storybook` instead
make sure you run `npm install` first
