### ISSUE TITLE
How to active links dynamically without adding 'active' props menu or with 'active' props applied but detected automatically

### ISSUE THREAD

**Issue by emmannweb** [azouaoui-med/react-pro-sidebar#178]
**Describe the bug**
  [`&.active`]: {
          backgroundColor: 'red',
           color: 'green',
    },

And for the Menu:
`<MenuItem active component={<Link to="/seller/dashboard" />} icon={<DashboardIcon />}> Dashboard </MenuItem>
<MenuItem component={<Link to="/seller/orders" />} icon={<ReceiptIcon />}> Orders</MenuItem>`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by azouaoui-med** [comment]
if you are using react router, the active class will be added automatically, if not you need to use the active prop to add the relevant class to use it for styling

**Comment by emmannweb** [comment]
Well, thanks for answering! I remember, it worked on some previous version of React Router (6.6.2), With the version that i'm using it's not working, When i check in the source code in the browser, i don't see any active class added, i don't know what's going on. I have added the active class to test it.

**Comment by shivam-2701** [comment]
@azouaoui-med I am getting the following error when using <Link> element from react router inside MenuItem 

` validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at LinkWithRef (http://localhost:3000/static/js/bundle.js:57118:7)
    at span`

**Comment by vaynevayne** [comment]
same issue, i use react-router v6, can see any class added to dom

**Comment by danieleagle** [comment]
@blombosi, after spending several hours on this, changing from Link to NavLink totally solved it. Thank you so much.
