### ISSUE TITLE
SSR Bug while using react-pro-sidebar with react-bootstrap and next.js

### ISSUE THREAD

**Issue by Voroniyx** [azouaoui-med/react-pro-sidebar#179]
**Describe the bug**
Hey, I get a bug when I use SSR in Next.js using the SSRProvider from 'react-bootstrap'. I wrap a div with `head` (next/head) and a body tag inside the div. Inside this body tag is a custom tag `SideBar` and a `Container` (react-bootstrap).

The Error
```
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching <body> in <div>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Component Stack
body
div
$704cf1d3b684cc5c$export$9f8ac96af4b1b2ae
```
The link under `See more info here` is not helpful

**Screenshots**
![image](https://i.imgur.com/Poj6Pzt.png)
![image](https://i.imgur.com/BamrTOi.png)

**Comment by Voroniyx** [comment]
![image](https://i.imgur.com/sjcgMqr.png)

**Comment by estubmo** [comment]
Try adding the "use client" directive or wrapping it in a [ClientOnly wrapper](https://www.joshwcomeau.com/react/the-perils-of-rehydration/#abstractions).
