### ISSUE TITLE
Unable to use Open and onOpenChange on SubMenu to "force" one Submenu opening at a time

### ISSUE THREAD

**Issue by code4cake** [azouaoui-med/react-pro-sidebar#180]
**Description**

This is  might be a functionality question than a bug, I don't know if it is really a bug or maybe I'm not using those props correctly ? 

I'm trying to use the `open` and `onOpenChange`  to handle that only 1 accordion `SubMenu` is open at a time.  
I want to use that same logic when I have nested Submenus as well.

But for some reason, this is not working.

**To Reproduce**
 You can come to this [sandbox](https://codesandbox.io/p/sandbox/react-pro-sidebar-example-srp9gv?file=%2Fsrc%2FApp.tsx%3A9%2C1)
 
**Expected behavior**
I click a `SubMenu1`  and it opens, I click  `SubMenu2` and `SubMenu1` closes. Only 1 level can be open at a time. This include nested `SubMenus`

**Comment by hepter** [comment]
@code4cake Yes that's right. [sandbox](https://codesandbox.io/s/gracious-hugle-62x5p6?file=/src/App.js)
