### ISSUE TITLE
[Feature request] - Menu items search

### ISSUE THREAD

**Issue by mohsenomidi** [azouaoui-med/react-pro-sidebar#183]
**Is your feature request related to a problem? Please describe.**

Im my use case i have over than 50 menu items with sub menus, then user should remember the item place in menu and it is annoying to open all categories and find the right item 

**Describe the solution you'd like**

I need the search capability in top of the menu with realtime filtering
It helps user while typing the part of item name the menu automatically elapsed and shows only the match cases 

**Describe alternatives you've considered**

**Comment by sufyan297** [comment]
Hey @mohsenomidi ,
You can easily implement searching feature on your own, no need to add in this library. You can share the code probably i can help.
Thank you

**Comment by mohsenomidi** [comment]
Thanks for reply, actually my menu creation items are server side and client side changes dose not suitable fro my use case, I will close this issue for now.
