### ISSUE TITLE
Sidebar root element styling inaccessible

### ISSUE THREAD

**Issue by jerbourgeois** [azouaoui-med/react-pro-sidebar#196]
**Describe the bug**
When applying styles using the sidebarClasses object and accessing the root element, the styling rules are not applied to the element at all.

**To Reproduce**
1. Create Sidebar element
2. Add any styling to sidebarClasses.root through the rootStyles prop on the Sidebar element

**Expected behavior**
The added styles should be reflected on the root.

**Actual behavior** 
The root element preserves it's default styling rules with no changes.

**Comment by rclsilver** [comment]
Hi,

You could use the `&` target IMO:
```typescript
const MySidebar = () => {
  const rootStyles: CSSObject = {
    ["&"]: {
      borderRightStyle: "none",
    },
  };

  return <Sidebar rootStyles={rootStyles}></Sidebar>;
};
```
