### ISSUE TITLE
[Question] How to remove/change icon hover animation and toggle collapsed

### ISSUE THREAD

**Issue by NateJones96** [azouaoui-med/react-pro-sidebar#20]
Hey, just wondering how I should go turning off the 'swing' animation for the menu icons. I see the keyframes in the scss but don't see where it's being added in the jsx.

And I'm also trying to add the collapse button to the menu itself (similar to how YouTube does it with the burger menu on the top left that collapses/opens the sidebar). Do I just pass the collapsed=true boolean as a state change? I see how you did it in the demo with the button in Main.js and the actual sidebar in Aside.js, passing the state change. But unsure of if it works just like props/states or am I missing something? Thanks!

**Comment by azouaoui-med** [comment]
Hello,
you can disable or update the animation by using the selector below : 
```
.pro-sidebar.collapsed .pro-menu>ul>.pro-menu-item.pro-sub-menu:hover .pro-icon-wrapper .pro-icon {
    animation: none;
}
```

and for the collapse you can add the trigger anywhere you like, just pass in the `collapsed `state to `ProSidebar `as shown in the demo and toggle the state when clicking on the trigger button

**Comment by NateJones96** [comment]
Both solutions worked perfectly, thanks! Love the sidebar, really appreciate it!
