### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by ceron97** [azouaoui-med/react-pro-sidebar#203]
In upcoming Nextjs 13 releases, when using breakPoint, releases are executed on the server rendering.
This makes the window not exist in the code; add validation to verify that the window exists.

With this validation the problem should be resolved.
`typeof window !== 'undefined'`

**Screenshots**
![image](https://github.com/azouaoui-med/react-pro-sidebar/assets/66496687/f54eaf31-d0d8-4d5f-80c9-aa75d9579b3b)

**Comment by patrickfreitasdev** [comment]
Another "solution" is using "use client" to make the component render the client side, depending on the case will help, though it lost the advantage of SSR
