### ISSUE TITLE
Submenu and MenuItems with different font color

### ISSUE THREAD

**Issue by tinytini12** [azouaoui-med/react-pro-sidebar#204]
Hi! I need to set Submenus with white font color and menuItems with black font color. I tried with root styles but it seems to always take the parent color

```
<Sidebar backgroundColor="#004F9A" collapsed={collapsed}>
                <Menu>
                    <SubMenu icon={<Icon.Spark />} label={sidebarLabels.products}>
                        <MenuItem component={<Link to="/bulk-saleformats" />}>{sidebarLabels.saleFormats}</MenuItem>
                    </SubMenu>
                </Menu>
</Sidebar>
```

**Comment by azouaoui-med** [comment]
you can use `menuItemStyles` on `Menu` component for customization 

here is demo in storybook https://azouaoui-med.github.io/react-pro-sidebar/?path=/docs/menu--menu-item-styles
