### ISSUE TITLE
Fixed and collapsible sidebar.

### ISSUE THREAD

**Issue by chuboyo** [azouaoui-med/react-pro-sidebar#207]
Hi @azouaoui-med , nice work on this package.

I have tried making the sidebar fixed with css such that as page content scrolls, the sidebar remains in a fixed position.
With the sidebar fixed, it becomes non-collapsible.

It would be nice to have the position of the sidebar fixed and collapsible while allowing vertical overflow on the main page.

Thanks.

**Comment by LordHub** [comment]
I'm not sure of what's your configuration but overwriting this class did the trick for me
`.ps-sidebar-container {
    position: sticky !important;
    top: 0px;
    height: unset !important;
}`

**Comment by azouaoui-med** [comment]
thats more of a layout issue, the sidebar can be controlled by whatever layout you create around it
