### ISSUE TITLE
How to shift the pop out mobile menu down or up to prevent hiding

### ISSUE THREAD

**Issue by Bryson14** [azouaoui-med/react-pro-sidebar#209]
**Describe the bug**

Sub menus can have multiple children <MenuItems /> especially when managing multiple data sources. So in this case, when the data submenu is expanded in its mobile format, it hides part of the child menuItem under the nav bar.

**To Reproduce**

**Expected behavior**
If there was a way to shift that context menu down so that the top nav bar didn't hide it, that would be awesome!

**Screenshots**
![image](https://github.com/azouaoui-med/react-pro-sidebar/assets/43580701/4cfb0b27-4948-44aa-83d2-7928313687cf)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 120.0

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: OS 15
 - Browser Safari
 - Version ??

**Additional context**

**Comment by HavenSelph** [comment]
You could possibly change the z index of the submenu using css
