### ISSUE TITLE
When navigating in the page without using sidenav, the menus do not open up to reflect current page

### ISSUE THREAD

**Issue by barrychapman** [azouaoui-med/react-pro-sidebar#21]
When navigating via page links, the menu does not get updated accordingly. I have tried to override this behavior by adding the function to apply class: className={this.isExpanded(prop.children, 'open', 'closed').

However, this only applies the 'open' or 'closed' class to the `<li>` with class `pro-menu-item pro-sub-menu`. There are two child div's immediately under that `<li>:`

![image](https://user-images.githubusercontent.com/152958/97130185-0c1f5a00-1717-11eb-8407-3c812ec58d98.png)

The class `pro-inner-item` appears to be the label for the top level drop down. There is also one below it which appears to be the actual slider dropdown `react-slidedown`. This is what appears to be impacted by the setting of the option `defaultOpen`. As you can see in my code below, the `defaultOpen` is set to the boolean response of `isExpanded()`, which I have confirmed is being returned as `true`.

Currently, my menu is rendered from JSON data, where it loops over the menu items/children and creates the submenus like so:

```
createLinks = (...) => {
           if (prop.children) {
                return (
                    <>
                        <SubMenu
                            title={prop.name}
                            defaultOpen={this.isExpanded(prop.children, true)}
                            className={this.isExpanded(prop.children, 'open', 'closed') }
                            icon={faIcon}
                        >
                            {this.createLinks(prop.children)}
                        </SubMenu>
                    </>
                );
            }

            return (
                <MenuItem className={this.activeRoute(prop.layout + prop.path, 'active')} icon={<FontAwesomeIcon icon={prop.icon} />}>
                    <NavLink to={prop.layout + prop.path} activeClassName="">
                        <>
                            <span className="sidebar-mini-icon"></span>
                            <span className="sidebar-normal">{prop.name}</span>
                        </>
                    </NavLink>
                </MenuItem>
                )
            });
}
```

Then the render function...

```
                <SidebarContent>
                    <Menu iconShape="circle" popperArrow={true}>
                        {this.createLinks(this.props.routes)}
                    </Menu>
                </SidebarContent>
```

The menu renders fine structurally, but I cannot get this defaultOpen to be passed to the submenu's that open up either directly at the top level or any child thereafter. This results in the behavior acting such that if I click on a page link on the page itself, not the sidenav, it will take me there - but will not open up the appropriate page that I am on in the sidebar. I have also confirmed that the sidebar is rerendered on these page changes.

It may be worth noting, that I checked this out with React dev tools also - and saw the following:

**This image shows the parent `<SubMenu>` having `defaultOpen` passed 'true' correctly**
![image](https://user-images.githubusercontent.com/152958/97130796-c82d5480-1718-11eb-9943-7f3492bf8c99.png)

**This next image shows the anonymous `ForwardRef` under the `<SubMenu>` from previously. You can see `closed` is set to 'true' in the props on the right.**
![image](https://user-images.githubusercontent.com/152958/97130799-cbc0db80-1718-11eb-93b4-313e4f4071f1.png)

**Finally, the props of the `<SlideDownContent>` node show that it is closed.**
![image](https://user-images.githubusercontent.com/152958/97130804-cebbcc00-1718-11eb-933a-798361bd7da5.png)

I am pretty lost here, and I am not exactly sure where the root of this lies. It appears that the correct parameters are passed to enable this functionality. What do I need to do to get these menus to open? Thank you so much for this plugin and your time!

**Comment by azouaoui-med** [comment]
I couldn't reproduce the error; could you share a code sandbox highlighting the error !

**Comment by barrychapman** [comment]
@azouaoui-med  can <MenuItem> and <SubMenu>'s be siblings to eachother?

**Comment by azouaoui-med** [comment]
Yes they can

**Comment by omarbarbosa06** [comment]
How do you add the button so when it gets responsive, instead of just disappearing, a button like the one on the demo show up to bring back the sidebar when clicked?

**Comment by azouaoui-med** [comment]
You just need to apply the following css/sass on the toggle button

When using sass you just set the `breakpoint-*` variable, which should be the same as the breakpoint set on the sidebar, in the demo i used `breakpoint-md`

```scss
.btn-toggle {
    display: none;
}
 @media (max-width: $breakpoint-md) {
    .btn-toggle {
      display: initial;
    }
 }

```

**Comment by Tasin5541** [comment]
I have the same problem. I used the url to provide `defaultOpen` value and it works fine if I reload the page. But if I just navigate to another page through direct links (not through the sidebar), the appropriate `SubMenus` do not expand automatically eventhough `defaultOpen` is sent as true.

For example:
Say, I have 2 SubMenus,
- I select a child of the 1st submenu, 1st submenu is expanded by me because I had to select it's child (2nd submenu has `defaultOpen=false` at this point because I'm on a child page of the 1st submenu)
- Now let's say I press on a link that loads the page from a child of the 2nd submenu, The 2nd SubMenu now has `defaultOpen=true` but it still stays unexpanded.
- Now I reload the page and 2nd submenu is expanded

**Comment by Tasin5541** [comment]
@barrychapman I ended up wrapping the SideMenu in another component and updating the menu toggle based on defaultOpen value

```
function CSubMenu(props) {
  const { defaultOpen, icon, title, children } = props;
  const [open, setOpen] = useState<boolean>(defaultOpen);

  useEffect(() => {
    if (defaultOpen) {
      setOpen(true);
    }
  }, [defaultOpen]);

  const handleMenuToggle = (closed) => {
    setOpen(!open);
  };

  return (
    <SubMenu defaultOpen={defaultOpen} open={open} onOpenChange={handleMenuToggle} icon={icon} title={title}>
      {children}
    </SubMenu>
  );
}
```

**Comment by Tasin5541** [comment]
> @Tasin5541 have you tried using `open` prop instead of `defaultOpen` ?

If I use `open` prop, I'll have to manage separate states for them because I want to be able to collapse the menus as well. Which is why I had to wrap the `SubMenu` component in another component so I can update the `open` prop based on the `defaultOpen` prop.

**Comment by ZAIN-JAHAN** [comment]
When I click submenu item.the new page open.but the router link is not availabe on sub menu.

**Comment by azouaoui-med** [comment]
@ZAIN-JAHAN yes routerLink is not available on SubMenu component, not sure which case you would use router in SubMenu,
you could use `onClick` with `useNavigate` and that should work

**Comment by ZAIN-JAHAN** [comment]
> @ZAIN-JAHAN yes routerLink is not available on SubMenu component, not sure which case you would use router in SubMenu, you could use `onClick` with `useNavigate` and that should work

When I click submenu the new page open and submenu also open

**Comment by ZAIN-JAHAN** [comment]
> > @ZAIN-JAHAN yes routerLink is not available on SubMenu component, not sure which case you would use router in SubMenu, you could use `onClick` with `useNavigate` and that should work
> 
> When I click submenu the new page open and submenu also open

Router link props not available in sub menu
