### ISSUE TITLE
Sidebar bug in Next.js 14.1.0

### ISSUE THREAD

**Issue by Snarloff** [azouaoui-med/react-pro-sidebar#212]
Hello! 

I have a bug in the package using it in Next.js version 14. The bug is that when entering the mobile device, the sidebar should start closed since it is responsive. However, as shown in the image, it starts open, **not being responsive**. I ran the sidebar by taking **Playgroud.tsx** and putting it in a Next project.

**Screenshots**

![image](https://github.com/azouaoui-med/react-pro-sidebar/assets/46792575/cc17aaab-ebab-4128-bfd9-b26ee88db102)

**Running on**

Windows 11
Next.js 14.1.0
Components declares with "use client"

I carried out the same test with Vite and it ran normally, being responsive.

```
Warning: Prop `className` did not match. Server: "ps-sidebar-root text-default-500 h-screen css-1rwe39e" Client: "ps-sidebar-root ps-broken text-default-500 h-screen css-1rwe39e"
```

**Comment by azouaoui-med** [comment]
have you tried adding ['use client'](https://nextjs.org/docs/app/building-your-application/rendering/client-components) to the sidebar wrapper ?!

**Comment by Snarloff** [comment]
> have you tried adding ['use client'](https://nextjs.org/docs/app/building-your-application/rendering/client-components) to the sidebar wrapper ?!

Yes! In all components too, but the same error

**Comment by Snarloff** [comment]
Any news?

**Comment by Snarloff** [comment]
?

**Comment by RaFeNiX** [comment]
Could you replicate this out of the Playground @Snarloff ?
I Have had some issues with The playground on the past. Maybe something related to config as Next 14 brings up some big changes over settings.

**Comment by Snarloff** [comment]
> Could you replicate this out of the Playground @Snarloff ? I Have had some issues with The playground on the past. Maybe something related to config as Next 14 brings up some big changes over settings.

I replicated it in Playground and in my normal code and it gives this error :/

**Comment by jweekley7** [comment]
I having this issue too. Anyone made any progress yet?

**Comment by jweekley7** [comment]
This has something to do with the breakpoint. This is my workaround
<img width="325" alt="image" src="https://github.com/azouaoui-med/react-pro-sidebar/assets/91277836/07f75ab2-e65a-4eb4-b7f0-53c2f27c89ec">

**Comment by fchoi1** [comment]
A better workaround is to check for component mount since there is a mismatch in the classname for broken sidebar
since the useEffect is done on client side render

```
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

   return (mounted && (
      <Sidebar> .... <Sidebar/>))
 ```

**Comment by Yugi-2** [comment]
The "mounted" workaround was not preferable to me as there's an awkward second before the sidebar loads in. Instead I used CSS media queries to hide the sidebar on initial load when it is less than the breakpoint width

**Comment by pavel-vorobev-quantumsoft** [comment]
Same here. It falls into hydration issue:

```Warning: Prop `className` did not match. Server: "ps-sidebar-root ps-rtl css-1jlhf24" Client: "ps-sidebar-root ps-broken ps-rtl css-1jlhf24"```

It's also visible all the way without backdrop regardless of collapsed prop value.


"react-pro-sidebar": "^1.1.0",
"react": "^18",
"next": "14.2.2",

**Comment by hiep294** [comment]
I use css variables, and this fixed the issues
/// css file
--sidebar-bg: rgba(255, 255, 255, 0.9);
--sidebar-color: #607489;
--sidebar-menu-icon: #0098e5;
--sidebar-menu-disabled: #9fb6cf;

// jsx file
 const menuItemStyles: MenuItemStyles = useMemo(
    () => ({
      root: {
      icon: {
        color: "var(--sidebar-menu-icon)",
        [`&.${menuClasses.disabled}`]: {
          color: "var(--sidebar-menu-disabled)",
        },
      },
      SubMenuExpandIcon: {
        color: "var(--sidebar-sub-menu-span-icon)",
      },
      ...,
    [collapsed]
  );

**Comment by lockhaicttv** [comment]
I got the same issue, thanks all to make me know I am not alone T.T. The problem happen when I move project from vite to nextjs 14

**Comment by lockhaicttv** [comment]
> The "mounted" workaround was not preferable to me as there's an awkward second before the sidebar loads in. Instead I used CSS media queries to hide the sidebar on initial load when it is less than the breakpoint width

Could you show me how you check and hide the sidebar ? Thank you so much
