### ISSUE TITLE
Dark mode support?+

### ISSUE THREAD

**Issue by Britman72** [azouaoui-med/react-pro-sidebar#213]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by azouaoui-med** [comment]
Theming is open for devs to integrate and is very easy to implement
please check the [playground](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/storybook/Playground.tsx) which illustrate how to implement dark mode
