### ISSUE TITLE
Can't decrease sidebar width below 250px

### ISSUE THREAD

**Issue by Neuro8** [azouaoui-med/react-pro-sidebar#217]
**Describe the bug**

It is possible to increase the sidebar width above 250px without problem. However, when using rootStyles props and trying to decrease the sidebar width below 250px, only the color display will decrease in width but the sidebar object pushing onto other component get stuck at 250px. This can be seen with the default border that creates a vertical line representing the true border of the sidebar that won't go below 250px

**To Reproduce**
Just pass a width < 250px to the rootStyles as such :

    return (
        <Sidebar
         rootStyles={{
            [`.${sidebarClasses.container}`]: {
              width: 200,            
            },
          }}
          
        >

**Expected behavior**
It would be nice if the sidebar object did not have that minimum width of 250px

**Comment by azouaoui-med** [comment]
Sidebar component exposes a prop `width` that deals with that 

use `<Sidebar width="200px"` instead

please refer to the [docs / API](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/README.md#api) for more details
