### ISSUE TITLE
Open the Submenus on Hover

### ISSUE THREAD

**Issue by jpcanamaque** [azouaoui-med/react-pro-sidebar#228]
Do we have a feature that opens the submenus on hover when the sidebar menu is minimized? Based on my initial usage, and checking the documentation, we don't have a way to do that. It would be nice to have that feature. Thanks!

EDIT 1: I used `onMouseEnter` event as a work around. However, it only worked when the menu is not collapsed

**Comment by aguprado** [comment]
> Do we have a feature that opens the submenus on hover when the sidebar menu is minimized? Based on my initial usage, and checking the documentation, we don't have a way to do that. It would be nice to have that feature. Thanks!
> 
> EDIT 1: I used `onMouseEnter` event as a work around. However, it only worked when the menu is not collapsed

I need this too please

**Comment by seanrightsec** [comment]
I got this working by adding an extra className to the `SubMenu` and handling it with CSS.

My demo uses Tailwind, but the approach is the same either way: when you hover a `SubMenu` in a collapsed `SideBar`, I target the child element with classname `.ps-submenu-content` and force it to show using `visibility: visible`, which is the style that actually control whether the submenu items container is visible.

That’s also why `onMouseEnter` / `onMouseLeave` didn’t help, they only toggle the `open` prop, but they don’t override the CSS that’s hiding `.ps-submenu-content`.

```
      <SideBar collapsed>
        <Menu closeOnClick>
          <SubMenu label="Charts" open={true}>
            <MenuItem> Pie charts </MenuItem>
            <MenuItem> Line charts </MenuItem>
          </SubMenu>
          <MenuItem> Documentation </MenuItem>
          <MenuItem> Calendar </MenuItem>

          // Classname added in the following line.
          <SubMenu label="Charts" className='hover:[&>.ps-submenu-content]:visible!'>
            <MenuItem> Pie charts </MenuItem>
            <MenuItem> Line charts </MenuItem>
          </SubMenu>
        </Menu>
      </SideBar>
```
Later on, I looked into their code and I'm pretty sure they used `visibility: ${openWhenCollapsed ? 'visible' : 'hidden'}` to control the element, but sadly it's not open for customisation.

Btw, use these three classnames together for better user experience 
```
hover:[&>.ps-submenu-content]:visible! 
not-hover:[&>.ps-submenu-content]:invisible! 
[&>.ps-submenu-content]:-translate-x-1.5!
```

**Comment by seanrightsec** [comment]
> I got this working by adding an extra className to the `SubMenu` and handling it with CSS.
> 
> My demo uses Tailwind, but the approach is the same either way: when you hover a `SubMenu` in a collapsed `SideBar`, I target the child element with classname `.ps-submenu-content` and force it to show using `visibility: visible`, which is the style that actually control whether the submenu items container is visible.
> 
> That’s also why `onMouseEnter` / `onMouseLeave` didn’t help, they only toggle the `open` prop, but they don’t override the CSS that’s hiding `.ps-submenu-content`.
> 
> ```
>       <SideBar collapsed>
>         <Menu closeOnClick>
>           <SubMenu label="Charts" open={true}>
>             <MenuItem> Pie charts </MenuItem>
>             <MenuItem> Line charts </MenuItem>
>           </SubMenu>
>           <MenuItem> Documentation </MenuItem>
>           <MenuItem> Calendar </MenuItem>
> 
>           // Classname added in the following line.
>           <SubMenu label="Charts" className='hover:[&>.ps-submenu-content]:visible!'>
>             <MenuItem> Pie charts </MenuItem>
>             <MenuItem> Line charts </MenuItem>
>           </SubMenu>
>         </Menu>
>       </SideBar>
> ```
> 
> Later on, I looked into their code and I'm pretty sure they used `visibility: ${openWhenCollapsed ? 'visible' : 'hidden'}` to control the element, but sadly it's not open for customisation.
> 
> Btw, use these three classnames together for better user experience
> 
> ```
> hover:[&>.ps-submenu-content]:visible! 
> not-hover:[&>.ps-submenu-content]:invisible! 
> [&>.ps-submenu-content]:-translate-x-1.5!
> ```

Using the `rootStyles` prop could be a better solution as there'll be no forced styles in the code.
```
<SubMenu
            component={<NavLink to={'/isms-artefacts'} />}
            rootStyles={{
              ['&.' + menuClasses.subMenuRoot]: {
                backgroundColor: '#eaabff',
                color: '#9f0099',
                '&:hover': {
                  backgroundColor: '#eecef9',
                  ['& > .' + menuClasses.subMenuContent]: {
                    visibility: 'visible',
                    backgroundColor: '#eecef9',
                  }
                },
                '&:not(hover)': {
                  ['& > .' + menuClasses.subMenuContent]: {
                    visibility: 'hidden',
                  }
                }
              },
              ['& > .' + menuClasses.subMenuContent]: {
                translate: '-6px',
              }
            }}
            >
            <li>Title</li>
            <MenuItem> Pie charts </MenuItem>
            <MenuItem> Line charts </MenuItem>
          </SubMenu>
```
