### ISSUE TITLE
SubMenu Item Onclick Event Handle Problem 

### ISSUE THREAD

**Issue by OgurSeren** [azouaoui-med/react-pro-sidebar#23]
Hello,

I installed the structure and it is available. but there is something I want to do. I can run the onClick event on the MenuItem. But I want to run the onClick event on SubMenu and unfortunately it does not enter. Can you help me?

**Comment by tec-devel** [comment]
Hello,

have the same issue

may be this help to someone: temporary workaround (in my case - I try to handle logout-function) is a use **react-router** with action in component constructor...

**Comment by azouaoui-med** [comment]
Fixed in [v.0.5.0](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v.0.5.0)
