### ISSUE TITLE
Menu name does not get highlighted

### ISSUE THREAD

**Issue by mohitsolytics** [azouaoui-med/react-pro-sidebar#25]
Hello,

Use Case:
Menu
Submenu contains 3 items

User select 2nd item from submenu. The 2nd item gets highlighted (font and icons have color).

My query: Can we highlight Menu name too, when is submenu item is selected?

I have marked with red arrow.

PFA

![image](https://user-images.githubusercontent.com/71820240/101066767-b3b46580-35bc-11eb-97f7-63bc9a45e37f.png)

**Comment by mladimatija** [comment]
You can try to target this with CSS  until this enhancement is shipped. When SubMenu has class `open` adjust the `color` property to desired value with something like `.pro-sidebar .pro-sub-menu.open > .pro-inner-item .pro-item-content`.

**Comment by joesatriani10** [comment]
@mohitsolytics  Did you found the way to do it?
