### ISSUE TITLE
[Request]: Hide Sidebar SubMenus and MenuItems based on access

### ISSUE THREAD

**Issue by AlbinCederblad** [azouaoui-med/react-pro-sidebar#26]
Say you have a list of resources you want different users to have access to, 

Maybe you could send in an array of IDs to ProSidebar component, and also send an ID prop to each SubMenu and MenuItem, which will then render conditionally based on the given array of IDs.

I could do this myself, but it makes the code quite unreadable.

Do you think this is a good idea? If not, any suggestions how i could solve this in a nice way?

**Comment by Kenan-Hussein** [comment]
I solve that by adding auth: true to each item in menus = [ ].
then I change the status of this key in SidebarComponent in ngOnInit() after I get the logged in user role.
finaly in sidebar.component.html you can add somthing like "*ngIf="menu.type === 'header' && menu.auth === false""

that works perfectly for me.

**Comment by AlbinCederblad** [comment]
> 
> 
> I solve that by adding auth: true to each item in menus = [ ].
> then I change the status of this key in SidebarComponent in ngOnInit() after I get the logged in user role.
> finaly in sidebar.component.html you can add somthing like "*ngIf="menu.type === 'header' && menu.auth === false""
> 
> that works perfectly for me.

Not sure i understand exactly what you did... I think i would have to read the code to understand. Personally I just forked the repo and made my own implementation, which worked perfectly for my use case.

**Comment by dnairns-arch** [comment]
You can use a function to render additional menu items, and call it in the Menu Tree, to have it put in the appropriate MenuItems. I have ma nu items that show for only admin users. So the code looks like such:

`function AdminComponents() {`
`    const role = UserRole();`
`    if (user === 'admin'){`
`        return (`
`            <>`
`                <MenuItem icon={<FaUsersCog />}> User Management <Link to "/usermgmt' /></MenuItem>`
`            </>`
`        );`
`    } else {`
`        return <p />;`
`    }`
`}`


The actual sidebar function would look like this:

`const Sidebar = () => {`
 `   return (`
`        <ProSidebar>`
`            <SidebarContent>`
`                <Menu iconsShape="circle">`
`                    <MenuItem icon={<FaHome />}>Home<Link to="/home"></MenuItem>`
`                    {AdminComponents()}`   <-- [This is where the Admin Components are inserted.]
`                </Menu>`
`            </SidebarContent>`
`        </ProSidebar>`
`    )`
`}`
