### ISSUE TITLE
uncollapse results in page to scroll to top

### ISSUE THREAD

**Issue by wibed** [azouaoui-med/react-pro-sidebar#29]
when opening the the navbar

either toggling collapsed
or removing collapsed className

the page jumps to top.

reproduce:
1. scroll a bit
2. open sidebar

expected:
the page not to jump to top

actual behaviour:
page jumps to top

example: https://codepen.io/azouaoui-med/pen/wpBadb

**Comment by azouaoui-med** [comment]
This issue should be moved to [pro-sidebar-template](https://github.com/azouaoui-med/pro-sidebar-template/issues) repo
