### ISSUE TITLE
Scrollable list of submenu?

### ISSUE THREAD

**Issue by scombs97** [azouaoui-med/react-pro-sidebar#30]
A cool enhancement would to make the submenu only show a set amount of menu items at a time and if there are more than that amount, you are able to scroll through the menu items.

**Comment by mladimatija** [comment]
@scombs97 You can always use something like [react-scrollbars-custom](https://www.npmjs.com/package/react-scrollbars-custom) to limit the number of items displayed. For example if you want the sidebar to take the full height of viewport and if it exceeds that height it can be scrolled. Probably don't even need to use custom lib for this but when native scrollbar appears contents of sidebar shift a bit to accommodate the scrollbar, hence it's better to implement custom scrollbar.
