### ISSUE TITLE
hide sidebar and dealing as drawer  

### ISSUE THREAD

**Issue by Kenan-Hussein** [azouaoui-med/react-pro-sidebar#31]
How can hide sidebar or call toggleSidebar(); when click outside?

Also is it possible to open or close the sidebar as we do in a mobile app like drag it from the side?

**Comment by azouaoui-med** [comment]
You can add `breakpoint `prop to activate the toggling behavior, check the [API reference table](https://github.com/azouaoui-med/react-pro-sidebar#API) for more use cases

Unfortunately the drag behavior is not supported

**Comment by Misbah-Mushtaq** [comment]
Breakpoint not working 
Its only working for small screen
