### ISSUE TITLE
How to make the sidebar work correct in a page layout

### ISSUE THREAD

**Issue by mulgurul** [azouaoui-med/react-pro-sidebar#32]
Spent hours trying to get RPS working yesterday, in an Electron app.

Problem is it is not floating to the side as expected, not even showing the elements correct, but as plain list elements in the bottom of the page.

I have tried several ways, with simple solution like in readme.md and more advanced copying from demo solution. Have tried with css and scss, same issue. 

So fresh in the head this morning I tried to do minimal Stackblitz demo. Here it's the same problem. But at least it's keeping the sidebar stuff together in a black frame, but its not working as a SIDEBAR.

have tried to wrap it in div and aside element. No change.

I suspect that some styles needs to be applied to the outer elements for the sidebar to work. But just grabbing the demo css did not solve it. And if such styles are necessary for the component to work, then they should be part of documentation.

What am I doing wrong or is the latest release broken?

Here's a link to my [Stackblitz](https://react-j9y3er.stackblitz.io)

I have to give up on it for know, but to spare others time, then maybe correct the problem or documentation so it's clear how to make the component to work as a sidebar! That's the whole idea of the component right?

Best regards, Peter

**Comment by azouaoui-med** [comment]
The sidebar component doesn't come with layout styling, you need to add it into your own layout,
here is a simple [sandbox demo](https://codesandbox.io/s/infallible-cherry-o7oko?file=/src/App.js) that may help you get started, you may need to add additional styling according to your needs

I also have [css layout library](https://azouaoui-med.github.io/css-pro-layout/docs/) that you can check out

**Comment by mulgurul** [comment]
Thanks for the quick reply. I have now figured out what is necessary for the component to act correctly in a page layout.
Although I'm a bit unsure exactly what is required and what is not.
Right now I'm struggling with a simple way to use the menu items as buttons with click handlers and not as router Links. Do you think this is possible?

**Comment by azouaoui-med** [comment]
You can directly add `onClick` handler on the `MenuItem `component, no need for extra component

`<MenuItem onClick={()=>console.log('menu item clicked')}>Component 1</MenuItem>`

**Comment by mulgurul** [comment]
Thanks again for great response:-)
I tried that but maybe because I'm using the module in typescript I get the error as explained in previous message. I'm unfortunately still on novice level with regards to react/electron/typescript, so I don't quite understand why I can't decorate the MenuItem Element with the onClick attribute?

**Comment by beaniebag** [comment]
I just fell into this problem too.  MenuItem doesn't have a prop for onClick.  To get around this wrap the element you want to be clickable in a div tag that supports onClick. e.g.
<div onClick={()=>console.log('menu item clicked')}>
  <MenuItem>Component 1</MenuItem>
</div>

**Comment by mulgurul** [comment]
Yes, that's one easy way. I found a solution if you want to avoid this. I t can help you with adding styles, classes etc. as well when using the sidebar in Typescript.

[This question helped me on the way](https://stackoverflow.com/questions/48240449/type-is-not-assignable-to-type-intrinsicattributes-intrinsicclassattribu) 

Declare an interface:
```
interface AttributeDictionary {
  [Key: string]: HTMLAttributes<typeof MenuItem>;
}
```
inside your class add this property where you define your custom attributes, mine is 'draggable':
```
attributes: AttributeDictionary = {
    menuitemattribute: {
      draggable: 'true',
    },
  };
```
Then expand or set it in the target Sidebar element:

`<MenuItem {...this.attributes.menuitemattribute}>`

Then it works as expected.

Hope this helps other..

Best regards, Peter Meldgaard

**Comment by azouaoui-med** [comment]
You can now use `onClick`  and any `HTML` event in [v0.6.0](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v.0.6.0)
