### ISSUE TITLE
Multiple menu expanded

### ISSUE THREAD

**Issue by shantinath** [azouaoui-med/react-pro-sidebar#33]
When i expand one menu, other opened menu should be collapsed. could you please fix this issue

**Comment by mladimatija** [comment]
If the menus you are trying to toggle are in the located in the same component next to each other you could refactor that code to use one menu and multiple SubMenu components (with additional SubMenus inside top level SubMenu items) and play around with `defaultOpen `and `open` properties.

You could save the identificatior of each SubMenu in a variable with `useState` hook, update the value on submenu toggle and add checks to `open` and possibly `defaultOpen` SubMenu properties.
