### ISSUE TITLE
Unable to reduce width, as min-width prop is not available

### ISSUE THREAD

**Issue by vamsikankipati** [azouaoui-med/react-pro-sidebar#35]
https://github.com/azouaoui-med/react-pro-sidebar/blob/f1dadc9503548e1c1921990af8009d224611415a/src/ProSidebar/ProSidebar.tsx#L59

Able to pass width prop to reduce the sidebar width, but not working. When tried adding min-width less than 270px default value, then it's working in browser.

is there a different way to reduce width of Sidebar ?

**Comment by azouaoui-med** [comment]
you can override the sidebar width css like so : 
```
.pro-sidebar {
  width: <you desired width>;
}
```
in the next release (few days) you will be able to use `width`  and `collapsedWidth`  props to setup your desired sidebar size without using css

**Comment by azouaoui-med** [comment]
fixed in [v0.6.0](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v.0.6.0)

**Comment by vamsikankipati** [comment]
thanks for quick fix!
