### ISSUE TITLE
Sidebar menu briefly pops up when transitioning from collapsed state

### ISSUE THREAD

**Issue by davipk** [azouaoui-med/react-pro-sidebar#36]
For some reason, any sub menu items that are inside a menu seems to pop up for a frame or so when transitioning from collapsed to a regular state. Any reason how this could be happening?

https://user-images.githubusercontent.com/1755890/109116463-335a5800-7706-11eb-9a2c-db20f60541b7.mp4

I've used the styles that's been imported by default then modified some variables. Tested the vanilla style as well and that also seems to cause the same issue.

**Comment by tommyphira** [comment]
I also had the same issue when switching from the switch in the demo to a button. I believe my issue was that the button doesn't have a 'checked' attribute so it will open the poppers for a brief second on click. To work around this, I left the code for the switch in, added my button to open the sidebar, and made the opacity of the original switch 0%. I'm sure you could probably create a function that modifies the state of collapsed but this was just a quick workaround.

**Comment by tommyphira** [comment]
I also had the same issue when switching from the switch in the demo to a button. I believe my issue was that the button doesn't have a 'checked' attribute so it will open the poppers for a brief second on click. To work around this, I left the code for the switch in, added my button to open the sidebar, and made the opacity of the original switch 0%. You could probably create a function that modifies the state of collapsed to achieve the same thing but this was just a quick workaround.

**Comment by geetanshmalhotra** [comment]
Any fixes for this yet?

**Comment by tarikcaliskan** [comment]
I had the same issue, then tried to remove transition inside the `pro-inner-list-item` class, then added a transition-delay, maybe it is related to visibility transition.

**Comment by geetanshmalhotra** [comment]
> I had the same issue, then tried to remove transition inside the `pro-inner-list-item` class, then added a transition-delay, maybe it is related to visibility transition.

I tried implementing this. Removed all transitions from `pro-inner-list-item` and tried adding transition delay. Glitch still seems to be there.

**Comment by egmab** [comment]
I had the same issue and added this in my css menu file :
`.pro-sidebar:not(.collapsed) .popper-inner {
    display: none;
}`
It seems to stop the glitch and can work as a temporary solution until the issue is fixed

**Comment by ffendt** [comment]
This issue still exists, only that the temporary solution does no longer work.
