### ISSUE TITLE
Css issus

### ISSUE THREAD

**Issue by priyankush-siloria** [azouaoui-med/react-pro-sidebar#46]
Thanks for such great sidebar. It helped me a lot but i have issue with css, I want to change the colour of side bar without using !important, @azouaoui-med  can you help me with this. 

I am using css in my project but as mentioned here 
![Screenshot from 2021-04-21 12-15-25](https://user-images.githubusercontent.com/44189293/115508864-6864d000-a29b-11eb-8aae-a2022241405b.png), i have created a custom.scss file add change color to #ffffff but still not able to change the color of sidebar

**Comment by azouaoui-med** [comment]
using scss variable should override the default `sideba-bg-color`
here is an example in the demo [https://github.com/azouaoui-med/react-pro-sidebar/blob/master/demo/src/styles/App.scss](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/demo/src/styles/App.scss)

**Comment by ediopia** [comment]
It cannot overwrite $sidebar-color
