### ISSUE TITLE
I don't see mobile menu

### ISSUE THREAD

**Issue by lsiadaczka** [azouaoui-med/react-pro-sidebar#47]
I don't see mobile menu like below

![obraz](https://user-images.githubusercontent.com/79289002/115920258-3bbadf00-a47a-11eb-9718-26879fa74b8a.png)

I set \<ProSidebar breakPoint= "sm"\> and your side menu disepear when I watch it on mobile phone.
How to fix it, please?

**Comment by marcnjaramillo** [comment]
I was looking into this myself just now, and it seems that this package only contains code for the sidebar and the functions necessary for making the sidebar responsive. When you inspect the toggle button in the developer console of your browser, you can see that the button is actually part of the main body code and not the sidebar menu. If you open up the source code for the live demo, you can see how the responsive layout functionality is implemented.

**Comment by AliFahmy** [comment]
@lsiadaczka did you find any solution for this issue ?

**Comment by lsiadaczka** [comment]
No, and you?

wt., 9 sie 2022, 15:21 użytkownik Ali Khalifa ***@***.***>
napisał:
