### ISSUE TITLE
How can I leave the SubMenuItem icons visible even the sidebar is collapsed

### ISSUE THREAD

**Issue by achraftarifa98** [azouaoui-med/react-pro-sidebar#59]
hello, I need to make the SubMenuItem icons visible when the sidebar is collabsed, so The subMenu needs to stay open even if I close the SideBar. 
any thoughts ?
thanks!

**Comment by azouaoui-med** [comment]
Submenus are displayed as popups on first level menu click when sidebar is collapsed ! what you are looking is a different behavior which is not supported in this package

**Comment by pateljoel** [comment]
@azouaoui-med Is there any way to show submenu icons in a collapsed state??
