### ISSUE TITLE
SubMenu level not indicate chevron icon

### ISSUE THREAD

**Issue by bogdanbaghiu** [azouaoui-med/react-pro-sidebar#60]
When there is another child submenu within a submenu, the last submenu does not have the display icon like the parent submenu does.

The example is seen in the demo where the MultiLevel does have the chevron but SubMenu3 does not.

It would be interesting if it were included.

![image](https://user-images.githubusercontent.com/37840937/125936541-037712e0-ccc4-407f-bc35-5a5fc4e7766e.png)

**Comment by OptivolveMohdIqbal** [comment]
i manage to show the chevron icon by customize the CSS below:

`/* Customize the SVG icon for project site & camera list */
.pro-sidebar.custom-sidebar
  .pro-menu-item.pro-sub-menu.custom-project-site-sub-menu
  .pro-inner-item::before {
  /* content: url('data:image/svg+xml; utf8, <svg stroke="white" fill="white" stroke-width="0" viewBox="0 0 448 512" class="test" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M436 480h-20V24c0-13.255-10.745-24-24-24H56C42.745 0 32 10.745 32 24v456H12c-6.627 0-12 5.373-12 12v20h448v-20c0-6.627-5.373-12-12-12zM128 76c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12V76zm0 96c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12v-40zm52 148h-40c-6.627 0-12-5.373-12-12v-40c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40c0 6.627-5.373 12-12 12zm76 160h-64v-84c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v84zm64-172c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12v-40c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40zm0-96c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12v-40c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40zm0-96c0 6.627-5.373 12-12 12h-40c-6.627 0-12-5.373-12-12V76c0-6.627 5.373-12 12-12h40c6.627 0 12 5.373 12 12v40z"></path></svg>') !important; */
  content: none !important;
  display: inline-flex !important;
  width: 0 !important;
  min-width: 0 !important;
  height: 14px !important;
  border: none !important;
  border-radius: 0 !important;
  box-shadow: none !important;
  margin-right: 30px !important;
}

.pro-sidebar.custom-sidebar
  .pro-menu-item.pro-sub-menu.custom-project-site-sub-menu
  .pro-menu-item.custom-camera-sub-menu
  .pro-inner-item::before {
  /* content: url('data:image/svg+xml; utf8, <svg stroke="white" fill="white" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg"><path d="M512 144v288c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V144c0-26.5 21.5-48 48-48h88l12.3-32.9c7-18.7 24.9-31.1 44.9-31.1h125.5c20 0 37.9 12.4 44.9 31.1L376 96h88c26.5 0 48 21.5 48 48zM376 288c0-66.2-53.8-120-120-120s-120 53.8-120 120 53.8 120 120 120 120-53.8 120-120zm-32 0c0 48.5-39.5 88-88 88s-88-39.5-88-88 39.5-88 88-88 88 39.5 88 88z"></path></svg>') !important; */
  content: none !important;
  display: inline-flex !important;
  width: 0 !important;
  min-width: 0 !important;
  height: 14px !important;
  border: none !important;
  border-radius: 0 !important;
  box-shadow: none !important;
  margin-right: 30px !important;
}

.pro-sidebar
  .pro-menu
  .pro-menu-item.pro-sub-menu
  .pro-inner-list-item
  .pro-inner-item
  .pro-arrow-wrapper,
.pro-sidebar
  .pro-menu
  .pro-menu-item.pro-sub-menu
  .pro-inner-list-item
  .pro-inner-item
  > .pro-icon-wrapper {
  display: block !important;
}`

The above CSS also helps to display the icon designated for every submenu as reported in issue #73

**Comment by azouaoui-med** [comment]
fixed in [v0.7.0](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v0.7.0)
