### ISSUE TITLE
Sidebar not occupying 100% height

### ISSUE THREAD

**Issue by diegoSenra** [azouaoui-med/react-pro-sidebar#63]
Hi!
Starting a new project and using this sidebar component, but my sidebar does not occupy 100% height of the screen.
What can be happening?
I don't have any styling in body

**Comment by azouaoui-med** [comment]
you set the body height to take full screen's height, the sidebar's parent needs to be full height so it can stretch 
make sure to check the demo folder for reference !

**Comment by diegoSenra** [comment]
Solved, thanks!

**Comment by mjarpitanand** [comment]
.pro-sidebar{
      height:100vh !important;
  }
This will solve your issue.
