### ISSUE TITLE
Sidebar menu close when going to new page.

### ISSUE THREAD

**Issue by barat95** [azouaoui-med/react-pro-sidebar#64]
Can you please tell me if i want to create multiple page and when i go to new page the sidebar menu is closed, because im creating a layout page where my sidebar is render on every new page click, can you please tell me where i can put my sidebar so that its not render everytime.

**Comment by azouaoui-med** [comment]
you may need to have the sidebar outside of your routing handler, you can have a layout with the sidebar and add a content component which handles page routing

**Comment by barat95** [comment]
Can you please give any example it will really help me.

**Comment by azouaoui-med** [comment]
if you check the demo folder ! routing can be added to [Main.js](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/demo/src/Main.js) component which is separated from Aside.js(sidebar)

**Comment by barat95** [comment]
I'm confused here because i want to create a master layout page to use same sidebar or different pages so my sidebar and header will not change only the content area will change, can you please give any example, or i can share my code pictures?

**Comment by azouaoui-med** [comment]
you can share a Code Sandbox with your current layout so we can point out the issue

**Comment by barat95** [comment]
Can i send you zip file without node_modules so i can check it if possible?

**Comment by barat95** [comment]
[demo.zip](https://github.com/azouaoui-med/react-pro-sidebar/files/6965841/demo.zip)

This is my project zip file can you please check it the problem is with sidebar i need some issues to be fixed like,
1. When i switch pages from dropdown the dropdown should not be closed.
2. On refresh page the active dropdown should retain its state to show open of which its sub menu is selected.

**Comment by barat95** [comment]
Can you please help me in this regard please? i really need it urgently for my project.

**Comment by jh250556** [comment]
What worked for me is to assign a unique, but non-changing (non system-generated) key to any/all Menu, SubMenu an MenuItem components.

**Comment by jacky4566** [comment]
Hey [azouaoui-med](https://github.com/azouaoui-med) I am also learning React and struggling to add pages to your demo code. It would be most appreciated if you could add some pages to your example. Just to show how routing could work with this sidebar.

**Comment by isabellachen** [comment]
> if you check the demo folder ! routing can be added to [Main.js](https://github.com/azouaoui-med/react-pro-sidebar/blob/master/demo/src/Main.js) component which is separated from Aside.js(sidebar)

How does this work? If the sidebar uses the <Link> element from react-router-dom, it needs to be wrapped with the <RouterProvider>. This seems to be such a fairly common usecase I'm surprised there isn't a straightforward solution out there. If you can give me more clues, I'll be glad to do a codesandbox to answer this question. Right now I can only think of storing the values in local storage or in a Context.

**Comment by isabellachen** [comment]
It now seems quite trivial to do this. I was able to do it by following the [docs of react router 6.8.3](https://reactrouter.com/en/main/start/tutorial)

My working codesandbox:
https://codesandbox.io/s/react-pro-sidebar-with-nesting-and-routing-and-submenu-not-collapsing-f3q27b

**Comment by isabellachen** [comment]
If you don't want to re-do your routing you can also get the pathname with react-router-dom's `useLocation()`and use the defaultOpen property, like so.

```tsx
<SubMenu
            label="Contacts"
            defaultOpen={currentPath.startsWith("/contacts")}
            icon={<i className="ti-layout-grid2"></i>}
          >
            <MenuItem
              active={currentPath === "/contacts/isa"}
              component={<Link to="/contacts/isa" />}
            >
              Isa
            </MenuItem>
          </SubMenu>
```
