### ISSUE TITLE
Sidebar sticky on scroll

### ISSUE THREAD

**Issue by KaiyaToast** [azouaoui-med/react-pro-sidebar#69]
Based on your demo code, to get the sidebar to stick while scrolling is to use overflow-y on the main component. It works normally on desktop but when accessing the page on mobile, the address & bottom bar of the browser UI will persist (tested on safari & chrome) on scroll. Usually it should automatically collapse. In addition, when scrolling to the end of the page it will cause  the content to be cut off. The same thing will happen when you scroll back up. Is there any work around for this?

**Comment by AliFahmy** [comment]
I know its late but apply this styles to your menu  
```
position: -webkit-sticky;
  position: sticky;
  top: 0;
```

**Comment by jack-sparroow** [comment]
@KaiyaToast  Can you provide the code here ?

**Comment by joesatriani10** [comment]
> 

How can I do that?

**Comment by dolevelbaz** [comment]
Does anyone has a code example resolving this for desktop?

I've tried the following but scrolling clips the sidebar:
```
<Sidebar
    rootStyles={{
        overflowY: "visible",
    }}
>
```

**Comment by allan-vera** [comment]
Anyone know of any simple solutions for this?

EDIT: did this
```

rootStyles={{
        position: "sticky",
        top: 0,
        height: "100vh",
      }}
```
