### ISSUE TITLE
Submenu icons not display as configured. Instead it using the bullet point.

### ISSUE THREAD

**Issue by OptivolveMohdIqbal** [azouaoui-med/react-pro-sidebar#73]
Hi, Thanks for the great sidebar function.

However, I have challenges when I try to show icons for the submenu. Even though I've specified the value for icon property at every submenu & submenu item, the icons do not display.

<SubMenu
            key={menu[0].projectSiteGuid}
            title={menu[0].projectSiteName}
            icon={<FaIcons.FaBuilding/>}
            defaultOpen={currentLocation.includes("camera-view")}
            className="custom-project-site-sub-menu"
          >
MenuItem
                  key={menu.macAddress}
                  active={currentLocation === `/camera-view/${menu.macAddress}`}
                  icon={<FaIcons.FaCamera />}
                  onClick={setMenuToActive}
                  className="custom-camera-sub-menu"
                >
                  {menu.name}
                  <Link to={`/camera-view/${menu.macAddress}`}></Link>
                </MenuItem>
</SubMenu>

![image](https://user-images.githubusercontent.com/42335678/132558069-eab078f3-17e5-4211-874e-b918aa4bea66.png)

The sidebar looks like this:

![image](https://user-images.githubusercontent.com/42335678/132558204-2c3cb236-7725-4bd5-a82c-cfb8a75cde79.png)

I'm not sure if I do this right or not, but I manage to get this fixed but customize the styling in CSS using my custom class.

![image](https://user-images.githubusercontent.com/42335678/132558329-63e6255e-4121-4038-a745-d2ca4051a3ef.png)

The sidebar now looks like this:

![image](https://user-images.githubusercontent.com/42335678/132558377-a8e6ec55-9573-4d7f-81b8-eaeca6378c5c.png)

Appreciate your help to clarify this. Thanks.

**Comment by azouaoui-med** [comment]
i didn't had the intention to use icons inside submenu items, but since there are a lot of requests about this, it will be enabled in the next release !

**Comment by azouaoui-med** [comment]
fixed in [v0.7.0](https://github.com/azouaoui-med/react-pro-sidebar/releases/tag/v0.7.0)
