### ISSUE TITLE
Image in place of sidemenu Icon

### ISSUE THREAD

**Issue by Misbah-Mushtaq** [azouaoui-med/react-pro-sidebar#74]
I want to place custom image icons, how can I do that? this code snippet is not working for me 
@azouaoui-med 
`<MenuItem icon={<img src={pie} alt="awSnap" />} style={dashboardStyle}>
                      <Link
                        to="/MyDashboard"
                        onClick={() => handleToggleSidebar(false)}
                      >
                        Dashboard
                      </Link>
                    </MenuItem>`

**Comment by azouaoui-med** [comment]
using an image should work just fine ! just make sure to have the correct size of the image to fit inside the icon wrapper !

**Comment by praveenfzs** [comment]
@azouaoui-med icons tag not appear when using imagee
