### ISSUE TITLE
How do you use the Active prop?

### ISSUE THREAD

**Issue by ayush-lal** [azouaoui-med/react-pro-sidebar#75]
With multiple links in my side bar, im wondering how you could implement the 'Active' prop?

**Comment by memorx** [comment]
I think it is something like this:
<MenuItem active={window.location.pathname === "/home/"} icon={<IoHomeOutline />}>
  Home
  <Link to="/home" />
</MenuItem>

**Comment by memorx** [comment]
better answer: `<MenuItem active={window.location.pathname === '/' ? true : false} icon={<FiHome />}>
                <Link to="/">Home</Link>
              </MenuItem>
              <MenuItem active={window.location.pathname === '/devices' ? true : false} icon={<TbDeviceNintendo />}>
                <Link to="/devices">Devices</Link>
              </MenuItem>`

**Comment by aldwinp35** [comment]
The ``MenuItem`` component takes a ``routerLink`` prop where you can pass a [Link](https://reactrouter.com/en/main/components/link) or [NavLink](https://reactrouter.com/en/main/components/nav-link) component that will be used to handle routing. ``NavLink`` knows whether or not it is "active". So you can pass a function to either ``style`` or ``className`` that will allow you to customize the inline styling or the class string based on the component's active state. 

``MenuItem`` also takes a ``active`` prop that when it is set to true, the component is active.

To take advantage of this functionality of ``NavLink`` you can create a new component that embed ``MenuItem`` and create a state that is going to **set** the ``active`` prop of ``MenuItem`` whether it's true or false based on ``NavLink``.

```javascript
import { useState } from "react";
import { MenuItem } from "react-pro-sidebar";
import { NavLink } from "react-router-dom";

function MyMenuItem({ icon, text, to }) {
  const [active, setActive] = useState(false);

  return (
    <MenuItem
      active={active}
      icon={icon}
      routerLink={
        <NavLink
          to={to}
          className={({ isActive }) => setTimeout(() => setActive(isActive), 0)} // isActive will tell us if the NavItem is active or not
        />
      }
    >
      {text}
    </MenuItem>
  );
}

export default MyMenuItem;
``` 
Then you can import that component and use it in your sidebar

```javascript
import { Sidebar, Menu, useProSidebar } from "react-pro-sidebar";
import { FaChartPie } from "react-icons/fa";
import MyMenuItem from "./MyMenuItem";

const MySidebar = () => {
  const { collapsed } = useProSidebar();

  const myMenuItemStyles = (active) => ({
    ".menu-anchor": {
      backgroundColor: active ? "#444" : "initial",
      color: active ? "#eee" : "#ccc",
    },
    ".menu-anchor:hover": {
      backgroundColor: "#444",
      color: "#eee",
    },
  });

  return (
    <Sidebar
      id="sidebar"
      breakPoint="xl"
      backgroundColor="#272727"
    >
      <Menu renderMenuItemStyles={({ active }) => myMenuItemStyles(active)}>
        <MyMenuItem icon={<FaChartPie />} text="Dashboard" to="/dashboard" />
      </Menu>
    </Sidebar>
  );
};

export default MySidebar;


```
