### ISSUE TITLE
Can't use with NextJs!

### ISSUE THREAD

**Issue by darshantejani007** [azouaoui-med/react-pro-sidebar#76]
This is the issue: 

![ezgif-2-b06345c6e668](https://user-images.githubusercontent.com/6480543/134163316-906fdbaa-1992-4877-8da9-c5b71fd8fe79.gif)

Inside my `pages/_app.js` , I've added the  sidebar as following : 

```

import { ProSidebar, Menu, MenuItem, SubMenu } from 'react-pro-sidebar';
import 'react-pro-sidebar/dist/css/styles.css';


import Layout from '@/components/_App/Layout';

const MyApp = ({ Component, pageProps }) => {
    return (
        <>
        <ProSidebar>
            <Menu iconShape="square">
                <MenuItem >Dashboard</MenuItem>
                <SubMenu title="Components" >
                <MenuItem>Component 1</MenuItem>
                <MenuItem>Component 2</MenuItem>
                </SubMenu>
            </Menu>
        </ProSidebar>

        <Layout>
            <Component {...pageProps} />
        </Layout>

        </>
    )
}

export default MyApp;
```

I've tried several other combinations, like adding the code inside the `Layout.js` component etc. But the sidebar only appears at the top! Does this mean the library is incompatible with next.js?

**Comment by azouaoui-med** [comment]
this is a layout issue, you need to have a correct working layout where you can then put the sidebar inside the left box ! you can check the code in the [demo](https://github.com/azouaoui-med/react-pro-sidebar/tree/master/demo) for reference

**Comment by darshantejani007** [comment]
Yeah, copying majority of styling and making many changes **worked**. Though it was unclear from the documentation. Anyway thanks for the quick reply.

**Comment by mikku489** [comment]
not sure if it's a layout issue, I'm also having the exact same problem as OP with NextJS.

What is the NextJS equivalent of this wrapper?

```
import { ProSidebarProvider } from 'react-pro-sidebar';

<ProSidebarProvider>
  <App />
</ProSidebarProvider>;
```

**Comment by vinsis** [comment]
Hi @mikku489 this is how I made it work:

In file `_app.tsx` (or `_app.js` if you are not using typescript)
```typescript
function MyApp({ Component, pageProps }: AppProps) {
  return <ProSidebarProvider><Component {...pageProps} /></ProSidebarProvider>
}
