### ISSUE TITLE
Bullets in v0.7.0?

### ISSUE THREAD

**Issue by sm3sher** [azouaoui-med/react-pro-sidebar#81]
Hey there,
I was upgrading to the latest version and my sidebar changed completely.

Is it possible to still use the bullet-view for menuitems and submenu?

**Comment by azouaoui-med** [comment]
First upgrade to V 0.7.1 
arrows are now displayed by default in inner submenu elements, to keep the previous behavior you need to add the following props in Menu component 
```
<Menu subMenuBullets innerSubMenuArrows={false}> 
....
```

this update is made to enable use of icons in inner submenu elements

**Comment by sm3sher** [comment]
Thank you, issue is fixed
