### ISSUE TITLE
Show active state with link menu item

### ISSUE THREAD

**Issue by KingCrabSolutions** [azouaoui-med/react-pro-sidebar#84]
When menu items are used with `<Link to...>`, the currently "active" item isn't highlighted.  Not sure if this is a bug or a feature, but it would me great if could add support to recognize the selected "page".

**Comment by nvmnghia** [comment]
@KingCrabSolutions you found any solution yet? this should be considered a bug.

**Comment by alexazarh** [comment]
I'm having the same issue, anyone found a solution?
