### ISSUE TITLE
popper on sub menu is not working when using @casl/ability

### ISSUE THREAD

**Issue by muzamalidrees** [azouaoui-med/react-pro-sidebar#9]
Here is my code:

` <Can I='read' a='roles'>
                        <SubMenu
                            title={<Link to='/users/all'>Users</Link>}
                            icon={<i className="flaticon-multiple-users-silhouette h4 m-0 p-0" />}
                        >
                            <Can I='read' a='roles'>
                                <MenuItem>
                                    <Link to='/users/roles/all'>Roles</Link>
                                </MenuItem>
                            </Can>
                        </SubMenu>
                    </Can>`

It is working normally when not using [@casl/ability](https://stalniy.github.io/casl/v4/en/package/casl-react) but when i using this, popper menu on hover is not working...

**Comment by muzamalidrees** [comment]
@ azouaoui-med any suggestions?

**Comment by dprslt** [comment]
I think i have the same problem, SubMenu popper does not works if i  wrap them in another component

**Comment by launcherx** [comment]
@azouaoui-med Having the same issue, any updated?
