### ISSUE TITLE
Demo is pulling code from node modules

### ISSUE THREAD

**Issue by technumbers** [azouaoui-med/react-pro-sidebar#98]
Demo is pulling code from node modules. That way we are not allowed to modify the source code and see changes on the screen. Please update demo to pull code from source so we can see how the source is working instead of the npm package

**Comment by azouaoui-med** [comment]
If you want to use the source code directly you can use [yarn link](https://classic.yarnpkg.com/en/docs/cli/link) to link the demo project to the package
